"""
IR → Python Wrapper Code Generator

Generates a Python wrapper module (_wrapper.py) that:
- Re-exports all raw pybind11 bindings from _lvgl
- Adds convenience functions (color, run_loop, k230_driver_init, etc.)

Widget classes are NOT generated here because the raw pybind11 bindings
already provide factory functions (lv.Label(parent), lv.Button(parent), etc.)
that return Obj instances with all methods. Adding wrapper classes with the
same names would shadow these factory functions and break usage.
"""

from __future__ import print_function
from typing import Dict, List, Optional, Set

from lvgl_ir.schema import (
    ModuleIR, FunctionIR, WidgetIR, FuncCategory,
)


class PythonWrapperGenerator:
    """Generates Python wrapper code from ModuleIR."""

    def __init__(self, module_ir: ModuleIR):
        self.ir = module_ir
        self.output_lines: List[str] = []

    def generate(self) -> str:
        """Generate the complete Python wrapper module."""
        self._emit_header()
        self._emit_convenience_functions()

        return "\n".join(self.output_lines)

    def emit(self, line: str = ""):
        """Append a line to the output."""
        self.output_lines.append(line)

    # -----------------------------------------------------------------------
    # Header
    # -----------------------------------------------------------------------

    def _emit_header(self):
        self.emit('"""')
        self.emit("Pythonic LVGL wrapper layer.")
        self.emit("")
        self.emit("Re-exports all raw pybind11 bindings from _lvgl and adds convenience")
        self.emit("functions. Auto-generated by gen_pybind11.py (IR-based pipeline).")
        self.emit('"""')
        self.emit("")
        self.emit("from ._lvgl import *  # noqa: F401,F403 - re-export all raw bindings")
        self.emit("")

    # -----------------------------------------------------------------------
    # Convenience functions
    # -----------------------------------------------------------------------

    def _emit_convenience_functions(self):
        self.emit("def color(r, g, b):")
        self.emit('    """Create a color from RGB values (0-255)."""')
        self.emit("    return color_make(r, g, b)")
        self.emit("")
        self.emit("def color_from_hex(hex_value):")
        self.emit('    """Create a color from a hex value (e.g., 0xFF0000 for red)."""')
        self.emit("    return color_hex(hex_value)")
        self.emit("")
        self.emit("def run_loop():")
        self.emit('    """Enter the LVGL run loop."""')
        self.emit("    driver_backends_run_loop()")
        self.emit("")
        self.emit("def k230_init(v4l2_drm=None, v4l2_drm_run_flag=0):")
        self.emit('    """Initialize K230 display driver.')
        self.emit("")
        self.emit("    When v4l2_drm is provided, uses the K230 v4l2-drm backend (DRM_V4L2_K230)")
        self.emit("    which shares the DRM display with camera video. When v4l2_drm is None,")
        self.emit("    falls back to the standard Linux DRM backend.")
        self.emit("")
        self.emit("    Args:")
        self.emit("        v4l2_drm: A V4l2Drm object (from k230_v4l2_drm module), or None")
        self.emit("                  to use the default Linux DRM driver.")
        self.emit("        v4l2_drm_run_flag: Flag controlling v4l2-drm run behavior (default: 0).")
        self.emit('    """')
        self.emit("    if v4l2_drm is not None:")
        self.emit("        display_ptr = v4l2_drm.get_display_ptr()")
        self.emit("    else:")
        self.emit("        display_ptr = 0  # NULL pointer -> use default DRM backend")
        self.emit("    return k230_driver_init(display_ptr, v4l2_drm_run_flag)")
        self.emit("")
        self.emit("# No __all__ — let all names from ._lvgl (enums, constants, functions,")
        self.emit("# widget factories like Label, Button, etc.) and the convenience functions")
        self.emit('# above pass through naturally via "from _wrapper import *".')
