"""
IR → Python Wrapper Code Generator

Generates a Python wrapper module (_wrapper.py) that:
- Re-exports all raw pybind11 bindings from _lvgl
- Tags widget instances with their type for method dispatch
- Adds short-name method aliases on Obj that dispatch by type tag
- Adds convenience functions (color, run, init, etc.)
"""

from __future__ import print_function
from typing import Dict, List, Optional, Set, Tuple

from lvgl_ir.schema import (
    ModuleIR, FunctionIR, WidgetIR, FuncCategory,
)


class PythonWrapperGenerator:
    """Generates Python wrapper code from ModuleIR."""

    # All LVGL widget types — all factory functions get type-tagged
    ALL_WIDGET_TYPES = {
        "obj", "image", "animimg", "arc", "arclabel", "label", "bar",
        "canvas", "barcode", "button", "buttonmatrix", "calendar",
        "chart", "checkbox", "dropdown", "imagebutton", "keyboard",
        "led", "line", "list", "lottie", "menu", "menu_page",
        "menu_cont", "menu_section", "menu_separator", "msgbox",
        "qrcode", "roller", "scale", "slider", "spangroup", "textarea",
        "spinbox", "spinner", "switch", "table", "tabview", "tileview", "win",
    }

    def __init__(self, module_ir: ModuleIR):
        self.ir = module_ir
        self.output_lines: List[str] = []

    def generate(self) -> str:
        """Generate the complete Python wrapper module."""
        self._emit_header()
        self._emit_selector_enum()
        self._emit_convenience_functions()
        self._emit_widget_type_tagging()
        self._emit_short_method_aliases()
        self._emit_color_helpers()

        return "\n".join(self.output_lines)

    def emit(self, line: str = ""):
        """Append a line to the output."""
        self.output_lines.append(line)

    # -----------------------------------------------------------------------
    # Header
    # -----------------------------------------------------------------------

    def _emit_header(self):
        self.emit('"""')
        self.emit("Pythonic LVGL wrapper layer.")
        self.emit("")
        self.emit("Re-exports all raw pybind11 bindings from _lvgl and adds convenience")
        self.emit("functions. Auto-generated by gen_pybind11.py (IR-based pipeline).")
        self.emit('"""')
        self.emit("")
        self.emit("from ._lvgl import *  # noqa: F401,F403 - re-export all raw bindings")
        self.emit("")
        self.emit("")
        self.emit("# --- Widget type resolution ---")
        self.emit("#")
        self.emit("# Objects created via factory functions (lv.btn(), lv.arc(), ...) get a")
        self.emit("# _widget_type attribute set by the Python wrapper.  But objects received")
        self.emit("# in C callbacks (anim exec_cb, event_cb, etc.) are new LvObjWrapper")
        self.emit("# instances created on the C++ side and lack _widget_type.  For those,")
        self.emit("# we fall back to _infer_widget_type() which queries the LVGL object class.")
        self.emit("")
        self.emit("def _get_wt(self):")
        self.emit("    \"\"\"Return the widget type string, falling back to LVGL class inspection.\"\"\"")
        self.emit("    wt = getattr(self, '_widget_type', None)")
        self.emit("    if wt is not None:")
        self.emit("        return wt")
        self.emit("    return self._infer_widget_type()")
        self.emit("")

    # -----------------------------------------------------------------------
    # Style Selector enum
    # -----------------------------------------------------------------------

    def _emit_selector_enum(self):
        """Emit the SELECTOR enum to replace magic number 0 in style APIs.

        In LVGL, the style selector is a combination of part + state
        (lv_part_t | lv_state_t). The most common value is 0, which means
        LV_PART_MAIN | LV_STATE_DEFAULT. Exposing this as SELECTOR.DEFAULT
        makes the API self-documenting and extensible.
        """
        self.emit("")
        self.emit("")
        self.emit("# --- Style Selector enum ---")
        self.emit("#")
        self.emit("# Replaces magic number 0 in set_style_xxx(value, selector) calls.")
        self.emit("# selector = part | state (LVGL convention).")
        self.emit("# SELECTOR.DEFAULT = 0 = LV_PART_MAIN | LV_STATE_DEFAULT")
        self.emit("#")
        self.emit("import enum as _enum")
        self.emit("")
        self.emit("class SELECTOR(_enum.IntEnum):")
        self.emit('    """Style selector constants for set_style_xxx(value, selector).')
        self.emit("")
        self.emit("    Combines LVGL part and state into a single selector value.")
        self.emit("    DEFAULT = LV_PART_MAIN | LV_STATE_DEFAULT = 0.")
        self.emit("")
        self.emit("    Usage::")
        self.emit("")
        self.emit("        obj.set_style_bg_color(color, lv.SELECTOR.DEFAULT)")
        self.emit("        # Equivalent to: obj.set_style_bg_color(color, 0)")
        self.emit("")
        self.emit("    For part+state combinations, use bitwise OR::")
        self.emit("")
        self.emit("        obj.set_style_bg_color(color, lv.PART.KNOB | lv.STATE.FOCUSED)")
        self.emit('    """')
        self.emit("    DEFAULT = 0")
        self.emit("")
        self.emit("    @staticmethod")
        self.emit("    def _combine(part, state=0):")
        self.emit('        """Combine a part and state into a selector value."""')
        self.emit("        return part | state")
        self.emit("")

    # -----------------------------------------------------------------------
    # Convenience functions
    # -----------------------------------------------------------------------

    def _emit_convenience_functions(self):
        self.emit("def color(r, g, b):")
        self.emit('    """Create a color from RGB values (0-255)."""')
        self.emit("    return color_make(r, g, b)")
        self.emit("")
        self.emit("def color_from_hex(hex_value):")
        self.emit('    """Create a color from a hex value (e.g., 0xFF0000 for red)."""')
        self.emit("    return color_hex(hex_value)")
        self.emit("")
        self.emit("def color_from_hex_str(hex_str):")
        self.emit('    """Create a color from a hex string (e.g., "#ff0000" or "#FF0000")."""')
        self.emit("    return color_hex(int(hex_str.lstrip('#'), 16))")
        self.emit("")
        self.emit("import os as _os")
        self.emit("import time as _time")
        self.emit("")
        self.emit("def run():")
        self.emit('    """Enter the LVGL run loop (blocking).')
        self.emit("")
        self.emit("    Can be interrupted with Ctrl+C.")
        self.emit('    """')
        self.emit("    try:")
        self.emit("        while True:")
        self.emit("            idle = timer_handler()")
        self.emit("            _time.sleep(idle / 1000.0)")
        self.emit("    except KeyboardInterrupt:")
        self.emit("        _os._exit(0)")
        self.emit("")
        self.emit("def init(v4l2_drm=None, v4l2_drm_run_flag=0):")
        self.emit('    """Initialize K230 display driver.')
        self.emit("")
        self.emit("    When v4l2_drm is provided, uses the K230 v4l2-drm backend (DRM_V4L2_K230)")
        self.emit("    which shares the DRM display with camera video. When v4l2_drm is None,")
        self.emit("    falls back to the standard Linux DRM backend.")
        self.emit("")
        self.emit("    Args:")
        self.emit("        v4l2_drm: A V4l2Drm object (from k230_v4l2_drm module), or None")
        self.emit("                  to use the default Linux DRM driver.")
        self.emit("        v4l2_drm_run_flag: Reserved, currently unused (default: 0).")
        self.emit('    """')
        self.emit("    if v4l2_drm is not None:")
        self.emit("        display_ptr = v4l2_drm.get_display_ptr()")
        self.emit("    else:")
        self.emit("        display_ptr = 0  # NULL pointer -> use default DRM backend")
        self.emit("    return k230_driver_init(display_ptr, v4l2_drm_run_flag)")
        self.emit("")

    # -----------------------------------------------------------------------
    # Type tagging & short method aliases
    # -----------------------------------------------------------------------

    def _detect_method_collisions(self) -> Set[str]:
        """Detect python method names that collide across widgets."""
        name_to_widgets: Dict[str, Set[str]] = {}
        for widget_name, widget in sorted(self.ir.widgets.items()):
            if widget_name == "obj":
                continue
            if widget_name not in self.ALL_WIDGET_TYPES:
                continue
            for func in widget.methods:
                if func.skip or func.category == FuncCategory.CONSTRUCTOR:
                    continue
                py_name = func.python_name
                if py_name == "delete":
                    py_name = "delete_obj"
                name_to_widgets.setdefault(py_name, set()).add(widget_name)
        return {name for name, widgets in name_to_widgets.items()
                if len(widgets) > 1}

    def _collect_prefixed_methods(self) -> Dict[str, List[Tuple[str, str]]]:
        """Collect methods that were prefixed in the C++ layer due to collisions.

        The C++ layer prefixes colliding names with _widget_name (leading underscore
        to make them Python-private). The dispatch layer references these private
        names internally.
        """
        colliding_names = self._detect_method_collisions()
        result: Dict[str, List[Tuple[str, str]]] = {}

        for widget_name, widget in sorted(self.ir.widgets.items()):
            if widget_name == "obj":
                continue
            if widget_name not in self.ALL_WIDGET_TYPES:
                continue
            prefixed = []
            for func in widget.methods:
                if func.skip or func.category == FuncCategory.CONSTRUCTOR:
                    continue
                py_name = func.python_name
                if py_name == "delete":
                    py_name = "delete_obj"
                if py_name in colliding_names:
                    # Match the C++ layer naming: _widget_shortname
                    prefixed_name = "_%s_%s" % (widget_name, py_name)
                    prefixed.append((prefixed_name, py_name))
            if prefixed:
                result[widget_name] = prefixed
        return result

    def _emit_widget_type_tagging(self):
        """Wrap ALL widget factory functions to tag returned Obj with widget type.

        Every widget gets tagged (not just those with conflicting methods)
        because short-name dispatch methods need the type tag to work correctly.
        """
        self.emit("")
        self.emit("")
        self.emit("# --- Widget type tagging ---")
        self.emit("#")
        self.emit("# Wrap ALL factory functions to tag returned Obj instances with")
        self.emit("# their widget type. This allows short-name dispatch methods")
        self.emit("# (set_rotation, set_value, etc.) to call the correct prefixed")
        self.emit("# C++ method based on the widget type.")
        self.emit("")

        # obj is a class (not a factory function), patch __init__ to set _widget_type
        self.emit("# obj is a class (not a factory function), so we patch __init__ to set _widget_type")
        self.emit("try:")
        self.emit("    _obj_orig_init = obj.__init__")
        self.emit("    def _obj_patched_init(self, *args, **kwargs):")
        self.emit("        _obj_orig_init(self, *args, **kwargs)")
        self.emit("        self._widget_type = 'obj'")
        self.emit("    obj.__init__ = _obj_patched_init")
        self.emit("except NameError:")
        self.emit("    pass")
        self.emit("")

        for widget_name, widget in sorted(self.ir.widgets.items()):
            if widget_name == "obj":
                continue  # Already handled above
            if widget_name not in self.ALL_WIDGET_TYPES:
                continue
            # Only wrap if there's a factory function for this widget
            py_name = widget_name
            # Check that the factory function exists (has create_func)
            if not widget.create_func:
                continue
            self.emit("try:")
            self.emit("    _orig_factory_%s = %s" % (py_name, py_name))
            self.emit("    def %s(parent=None):" % py_name)
            self.emit("        obj = _orig_factory_%s(parent)" % py_name)
            self.emit("        obj._widget_type = '%s'" % widget_name)
            self.emit("        return obj")
            self.emit("except NameError:")
            self.emit("    pass")

    def _emit_short_method_aliases(self):
        """Add short-name methods on Obj that dispatch by _widget_type."""
        prefixed_methods = self._collect_prefixed_methods()
        if not prefixed_methods:
            return

        # Build: short_name -> {widget_name: prefixed_name}
        short_name_map: Dict[str, Dict[str, str]] = {}
        for widget_name, methods in sorted(prefixed_methods.items()):
            for prefixed_name, short_name in methods:
                short_name_map.setdefault(short_name, {})[widget_name] = prefixed_name

        self.emit("")
        self.emit("")
        self.emit("# --- Short-name method aliases on Obj ---")
        self.emit("#")
        self.emit("# These methods dispatch to the correct prefixed C++ method based")
        self.emit("# on the _widget_type tag. For example, set_rotation() calls")
        self.emit("# image_set_rotation() or arc_set_rotation() depending on the widget.")
        self.emit("")

        for short_name, widget_map in sorted(short_name_map.items()):
            self.emit("try:")
            if len(widget_map) == 1:
                widget_name, prefixed_name = list(widget_map.items())[0]
                self.emit("    def _%s_dispatch(self, *args, **kwargs):" % short_name)
                self.emit("        return self.%s(*args, **kwargs)" % prefixed_name)
            else:
                self.emit("    def _%s_dispatch(self, *args, **kwargs):" % short_name)
                self.emit("        _wt = _get_wt(self)")
                for widget_name, prefixed_name in sorted(widget_map.items()):
                    self.emit("        if _wt == '%s': return self.%s(*args, **kwargs)" % (widget_name, prefixed_name))
                self.emit("        raise AttributeError(\"Obj has no '%s' for widget type %%s\" %% _wt)" % short_name)
            self.emit("    obj.%s = _%s_dispatch" % (short_name, short_name))
            self.emit("except NameError:")
            self.emit("    pass")

        # Patch add_flag/remove_flag/set_flag/has_flag to accept int (from OBJ_FLAG | OBJ_FLAG)
        self.emit("")
        self.emit("# --- Bitmask enum patches ---")
        self.emit("#")
        self.emit("# pybind11 enum | returns int, not the enum type, so add_flag(OBJ_FLAG.A | OBJ_FLAG.B)")
        self.emit("# fails. Patch these methods to cast the int back to the enum type.")
        self.emit("")
        self.emit("try:")
        self.emit("    _orig_add_flag = obj.add_flag")
        self.emit("    def add_flag(self, f):")
        self.emit("        _orig_add_flag(self, OBJ_FLAG(int(f)))")
        self.emit("    obj.add_flag = add_flag")
        self.emit("except NameError:")
        self.emit("    pass")
        self.emit("try:")
        self.emit("    _orig_remove_flag = obj.remove_flag")
        self.emit("    def remove_flag(self, f):")
        self.emit("        _orig_remove_flag(self, OBJ_FLAG(int(f)))")
        self.emit("    obj.remove_flag = remove_flag")
        self.emit("except NameError:")
        self.emit("    pass")
        self.emit("try:")
        self.emit("    _orig_set_flag = obj.set_flag")
        self.emit("    def set_flag(self, f, v):")
        self.emit("        _orig_set_flag(self, OBJ_FLAG(int(f)), v)")
        self.emit("    obj.set_flag = set_flag")
        self.emit("except NameError:")
        self.emit("    pass")
        self.emit("try:")
        self.emit("    _orig_has_flag = obj.has_flag")
        self.emit("    def has_flag(self, f):")
        self.emit("        return _orig_has_flag(self, OBJ_FLAG(int(f)))")
        self.emit("    obj.has_flag = has_flag")
        self.emit("except NameError:")
        self.emit("    pass")
        self.emit("try:")
        self.emit("    _orig_has_flag_any = obj.has_flag_any")
        self.emit("    def has_flag_any(self, f):")
        self.emit("        return _orig_has_flag_any(self, OBJ_FLAG(int(f)))")
        self.emit("    obj.has_flag_any = has_flag_any")
        self.emit("except NameError:")
        self.emit("    pass")
        # Also patch add_state/remove_state for STATE enum
        self.emit("try:")
        self.emit("    _orig_add_state = obj.add_state")
        self.emit("    def add_state(self, s):")
        self.emit("        _orig_add_state(self, STATE(int(s)))")
        self.emit("    obj.add_state = add_state")
        self.emit("except NameError:")
        self.emit("    pass")
        self.emit("try:")
        self.emit("    _orig_remove_state = obj.remove_state")
        self.emit("    def remove_state(self, s):")
        self.emit("        _orig_remove_state(self, STATE(int(s)))")
        self.emit("    obj.remove_state = remove_state")
        self.emit("except NameError:")
        self.emit("    pass")

    # -----------------------------------------------------------------------
    # Obj method extensions & Color helpers
    # -----------------------------------------------------------------------

    def _emit_color_helpers(self):
        pass
