#include <linux/module.h>
#define INCLUDE_VERMAGIC
#include <linux/build-salt.h>
#include <linux/elfnote-lto.h>
#include <linux/export-internal.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

#ifdef CONFIG_UNWINDER_ORC
#include <asm/orc_header.h>
ORC_HEADER;
#endif

BUILD_SALT;
BUILD_LTO_INFO;

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__section(".gnu.linkonce.this_module") = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

#ifdef CONFIG_RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

KSYMTAB_FUNC(hbsle_hcc_customize_h2d_data_cfg, "", "");
KSYMTAB_FUNC(hbsle_hcc_custom_ini_data_buf, "", "");
KSYMTAB_FUNC(hbsle_hcc_customize_get_device_status, "", "");
KSYMTAB_FUNC(hbsle_hcc_customize_reset_device_status, "", "");
KSYMTAB_FUNC(reg_rw_check_addr, "", "");
KSYMTAB_FUNC(uapi_diag_report_sys_msg, "", "");
KSYMTAB_FUNC(diag_report_wlan_sample_data, "", "");
KSYMTAB_FUNC(diag_cmd_report_sample_data, "", "");
KSYMTAB_FUNC(diag_sample_data_register, "", "");
KSYMTAB_FUNC(uapi_efuse_read, "", "");
KSYMTAB_FUNC(uapi_efuse_write, "", "");
KSYMTAB_FUNC(efuse_write_dev_addr, "", "");
KSYMTAB_FUNC(efuse_write_spark_addr, "", "");
KSYMTAB_FUNC(efuse_write_pid_vid, "", "");
KSYMTAB_FUNC(uapi_efuse_get_lockstat, "", "");
KSYMTAB_FUNC(uapi_efuse_lock, "", "");
KSYMTAB_FUNC(hcc_get_tx_sched_num, "", "");
KSYMTAB_FUNC(hcc_message_register, "", "");
KSYMTAB_FUNC(hcc_message_unregister, "", "");
KSYMTAB_FUNC(hcc_get_head_len, "", "");
KSYMTAB_FUNC(hcc_init_ws73, "", "");
KSYMTAB_FUNC(hcc_deinit_ws73, "", "");
KSYMTAB_FUNC(hcc_enable_switch, "", "");
KSYMTAB_FUNC(hcc_enable_rx_thread, "", "");
KSYMTAB_FUNC(hcc_enable_tx_thread, "", "");
KSYMTAB_FUNC(hcc_stop_xfer_etc, "", "");
KSYMTAB_FUNC(hcc_resume_xfer_etc, "", "");
KSYMTAB_FUNC(hcc_switch_status, "", "");
KSYMTAB_FUNC(hcc_tx_data, "", "");
KSYMTAB_FUNC(hcc_bt_tx_data, "", "");
KSYMTAB_FUNC(hcc_send_message, "", "");
KSYMTAB_FUNC(hcc_read_reg, "", "");
KSYMTAB_FUNC(hcc_write_reg, "", "");
KSYMTAB_FUNC(hcc_get_pkt_max_len, "", "");
KSYMTAB_FUNC(hcc_get_channel_align_len, "", "");
KSYMTAB_FUNC(hcc_set_tx_sched_count, "", "");
KSYMTAB_FUNC(hcc_chan_is_busy, "", "");
KSYMTAB_FUNC(hcc_get_state_ws73, "", "");
KSYMTAB_FUNC(hcc_get_handler, "", "");
KSYMTAB_FUNC(hcc_flow_ctrl_set_water_line, "", "");
KSYMTAB_FUNC(hcc_flow_ctrl_get_water_line, "", "");
KSYMTAB_FUNC(hcc_flow_ctrl_credit_register, "", "");
KSYMTAB_FUNC(hcc_flow_ctrl_credit_unregister, "", "");
KSYMTAB_FUNC(sdio_exit_module, "", "");
KSYMTAB_FUNC(hcc_service_update_credit, "", "");
KSYMTAB_FUNC(hcc_service_init, "", "");
KSYMTAB_FUNC(hcc_service_deinit, "", "");
KSYMTAB_FUNC(hcc_test_proc_local_cmd, "", "");
KSYMTAB_FUNC(hcc_test_proc_remote_cmd, "", "");
KSYMTAB_FUNC(get_cust_conf_int32_etc, "_gpl", "");
KSYMTAB_FUNC(ini_file_check_conf_update, "_gpl", "");
KSYMTAB_FUNC(get_cust_conf_string_etc, "_gpl", "");
KSYMTAB_FUNC(ini_get_cust_item_list, "_gpl", "");
KSYMTAB_FUNC(plat_parse_mac_addr, "", "");
KSYMTAB_FUNC(set_mac_derivation_ptr, "", "");
KSYMTAB_FUNC(get_dev_addr, "", "");
KSYMTAB_FUNC(set_dev_addr, "", "");
KSYMTAB_FUNC(memcpy_s_ws73, "", "");
KSYMTAB_FUNC(memmove_s_ws73, "", "");
KSYMTAB_FUNC(memset_s_ws73, "", "");
KSYMTAB_FUNC(oal_get_sysfs_root_object_etc, "", "");
KSYMTAB_FUNC(oal_put_sysfs_root_object_etc, "", "");
KSYMTAB_FUNC(oal_chip_get_version_etc, "", "");
KSYMTAB_FUNC(oal_chip_get_device_num_etc, "", "");
KSYMTAB_FUNC(oal_board_get_service_vap_start_id, "", "");
KSYMTAB_DATA(g_auc_wlan_service_device_per_chip_ws73, "", "");
KSYMTAB_FUNC(oal_get_wakelock_head, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_init_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_read_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_set_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_inc_return_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_dec_return_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_inc_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_dec_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_atomic_add_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_strncmp_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_kthread_create_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_get_current_tid_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_kthread_should_stop_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_kthread_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_kthread_set_priority_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_wait_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_wait_wakeup_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_timer_init_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_jiffies_to_msecs_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_timer_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_get_jiffies_ws73, "", "");
KSYMTAB_FUNC(osal_adapt_timer_mod_ws73, "", "");
KSYMTAB_FUNC(osal_kmalloc_ws73, "", "");
KSYMTAB_FUNC(osal_kfree_ws73, "", "");
KSYMTAB_FUNC(osal_vmalloc_ws73, "", "");
KSYMTAB_FUNC(osal_vfree_ws73, "", "");
KSYMTAB_FUNC(osal_copy_from_user_ws73, "", "");
KSYMTAB_FUNC(osal_copy_to_user_ws73, "", "");
KSYMTAB_FUNC(osal_access_ok_ws73, "", "");
KSYMTAB_FUNC(osal_phys_to_virt_ws73, "", "");
KSYMTAB_FUNC(osal_virt_to_phys_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_init_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_read_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_set_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_inc_return_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_dec_return_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_inc_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_dec_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_add_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_dec_and_test_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_inc_and_test_ws73, "", "");
KSYMTAB_FUNC(osal_atomic_inc_not_zero_ws73, "", "");
KSYMTAB_FUNC(osal_panic_ws73, "", "");
KSYMTAB_FUNC(osal_dump_stack_ws73, "", "");
KSYMTAB_FUNC(osal_printk_ws73, "", "");
KSYMTAB_FUNC(osal_klib_fopen_ws73, "", "");
KSYMTAB_FUNC(osal_klib_fclose_ws73, "", "");
KSYMTAB_FUNC(osal_klib_fwrite_ws73, "", "");
KSYMTAB_FUNC(osal_klib_fread_ws73, "", "");
KSYMTAB_FUNC(osal_klib_fseek_ws73, "", "");
KSYMTAB_FUNC(osal_klib_fsync_ws73, "", "");
KSYMTAB_FUNC(osal_klib_set_store_path_ws73, "", "");
KSYMTAB_FUNC(osal_klib_get_store_path_ws73, "", "");
KSYMTAB_FUNC(osal_irq_request_ws73, "", "");
KSYMTAB_FUNC(osal_irq_free_ws73, "", "");
KSYMTAB_FUNC(osal_irq_set_affinity_ws73, "", "");
KSYMTAB_FUNC(osal_in_interrupt_ws73, "", "");
KSYMTAB_FUNC(osal_irq_enable_ws73, "", "");
KSYMTAB_FUNC(osal_irq_disable_ws73, "", "");
KSYMTAB_FUNC(osal_tasklet_init_ws73, "", "");
KSYMTAB_FUNC(osal_tasklet_update_ws73, "", "");
KSYMTAB_FUNC(osal_tasklet_schedule_ws73, "", "");
KSYMTAB_FUNC(osal_tasklet_kill_ws73, "", "");
KSYMTAB_FUNC(osal_mutex_init_ws73, "", "");
KSYMTAB_FUNC(osal_mutex_lock_ws73, "", "");
KSYMTAB_FUNC(osal_mutex_lock_interruptible_ws73, "", "");
KSYMTAB_FUNC(osal_mutex_trylock_ws73, "", "");
KSYMTAB_FUNC(osal_mutex_unlock_ws73, "", "");
KSYMTAB_FUNC(osal_mutex_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_mutex_is_locked_ws73, "", "");
KSYMTAB_FUNC(osal_sem_init_ws73, "", "");
KSYMTAB_FUNC(osal_sem_down_ws73, "", "");
KSYMTAB_FUNC(osal_sem_down_timeout_ws73, "", "");
KSYMTAB_FUNC(osal_sem_down_interruptible_ws73, "", "");
KSYMTAB_FUNC(osal_sem_trydown_ws73, "", "");
KSYMTAB_FUNC(osal_sem_up_ws73, "", "");
KSYMTAB_FUNC(osal_sem_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_spin_lock_init_ws73, "", "");
KSYMTAB_FUNC(osal_spin_lock_ws73, "", "");
KSYMTAB_FUNC(osal_spin_lock_bh_ws73, "", "");
KSYMTAB_FUNC(osal_spin_unlock_bh_ws73, "", "");
KSYMTAB_FUNC(osal_spin_trylock_ws73, "", "");
KSYMTAB_FUNC(osal_spin_unlock_ws73, "", "");
KSYMTAB_FUNC(osal_spin_lock_irqsave_ws73, "", "");
KSYMTAB_FUNC(osal_spin_unlock_irqrestore_ws73, "", "");
KSYMTAB_FUNC(osal_spin_lock_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_spin_trylock_irq_ws73, "", "");
KSYMTAB_FUNC(osal_spin_trylock_irqsave_ws73, "", "");
KSYMTAB_FUNC(osal_memncmp_ws73, "", "");
KSYMTAB_FUNC(osal_memncmp_tmp_new_ws73, "", "");
KSYMTAB_FUNC(osal_strcmp_ws73, "", "");
KSYMTAB_FUNC(osal_strncmp_ws73, "", "");
KSYMTAB_FUNC(osal_strncmp_tmp_new_ws73, "", "");
KSYMTAB_FUNC(osal_strcasecmp_ws73, "", "");
KSYMTAB_FUNC(osal_strncasecmp_ws73, "", "");
KSYMTAB_FUNC(osal_strncasecmp_tmp_new_ws73, "", "");
KSYMTAB_FUNC(osal_strchr_ws73, "", "");
KSYMTAB_FUNC(osal_strnchr_ws73, "", "");
KSYMTAB_FUNC(osal_strrchr_ws73, "", "");
KSYMTAB_FUNC(osal_strstr_ws73, "", "");
KSYMTAB_FUNC(osal_strnstr_ws73, "", "");
KSYMTAB_FUNC(osal_strlen_ws73, "", "");
KSYMTAB_FUNC(osal_strnlen_ws73, "", "");
KSYMTAB_FUNC(osal_strpbrk_ws73, "", "");
KSYMTAB_FUNC(osal_strsep_ws73, "", "");
KSYMTAB_FUNC(osal_strspn_ws73, "", "");
KSYMTAB_FUNC(osal_strcspn_ws73, "", "");
KSYMTAB_FUNC(osal_memscan_ws73, "", "");
KSYMTAB_FUNC(osal_memcmp_ws73, "", "");
KSYMTAB_FUNC(osal_memchr_ws73, "", "");
KSYMTAB_FUNC(osal_memchr_inv_ws73, "", "");
KSYMTAB_FUNC(osal_strtoull_ws73, "", "");
KSYMTAB_FUNC(osal_strtoul_ws73, "", "");
KSYMTAB_FUNC(osal_strtol_ws73, "", "");
KSYMTAB_FUNC(osal_strtoll_ws73, "", "");
KSYMTAB_FUNC(osal_kthread_should_stop_ws73, "", "");
KSYMTAB_FUNC(osal_kthread_create_ws73, "", "");
KSYMTAB_FUNC(osal_kthread_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_kthread_set_priority_ws73, "", "");
KSYMTAB_FUNC(osal_get_current_tid_ws73, "", "");
KSYMTAB_FUNC(osal_kthread_set_affinity_ws73, "", "");
KSYMTAB_FUNC(osal_timer_init_ws73, "", "");
KSYMTAB_FUNC(osal_timer_mod_ws73, "", "");
KSYMTAB_FUNC(osal_timer_stop_ws73, "", "");
KSYMTAB_FUNC(osal_timer_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_msleep_ws73, "", "");
KSYMTAB_FUNC(osal_msleep_uninterruptible_ws73, "", "");
KSYMTAB_FUNC(osal_udelay_ws73, "", "");
KSYMTAB_FUNC(osal_mdelay_ws73, "", "");
KSYMTAB_FUNC(osal_jiffies_to_msecs_ws73, "", "");
KSYMTAB_FUNC(osal_msecs_to_jiffies_ws73, "", "");
KSYMTAB_FUNC(osal_gettimeofday_ws73, "", "");
KSYMTAB_FUNC(osal_get_jiffies_ws73, "", "");
KSYMTAB_FUNC(osal_rtc_time_to_tm_ws73, "", "");
KSYMTAB_FUNC(osal_wait_init_ws73, "", "");
KSYMTAB_FUNC(osal_wait_interruptible_ws73, "", "");
KSYMTAB_FUNC(osal_wait_uninterruptible_ws73, "", "");
KSYMTAB_FUNC(osal_wait_timeout_interruptible_ws73, "", "");
KSYMTAB_FUNC(osal_wait_timeout_uninterruptible_ws73, "", "");
KSYMTAB_FUNC(osal_wait_wakeup_ws73, "", "");
KSYMTAB_FUNC(osal_wait_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_workqueue_init_ws73, "", "");
KSYMTAB_FUNC(osal_workqueue_schedule_ws73, "", "");
KSYMTAB_FUNC(osal_workqueue_destroy_ws73, "", "");
KSYMTAB_FUNC(osal_workqueue_flush_ws73, "", "");
KSYMTAB_DATA(g_custom_cali_func, "_gpl", "");
KSYMTAB_DATA(g_custom_hmac_exit_later_func, "_gpl", "");
KSYMTAB_FUNC(set_custom_exit_later_func, "", "");
KSYMTAB_FUNC(set_custom_cali_func, "", "");
KSYMTAB_FUNC(firmware_sha256_checksum, "", "");
KSYMTAB_DATA(g_plat_loglevel_etc, "", "");
KSYMTAB_FUNC(uapi_drv_cipher_trng_get_random_bytes, "", "");
KSYMTAB_FUNC(uapi_ccpriv_suspend_system, "", "");
KSYMTAB_FUNC(uapi_ccpriv_resume_system, "", "");
KSYMTAB_FUNC(uapi_set_plat_ccpriv_opts, "", "");
KSYMTAB_FUNC(pm_svc_power_on, "", "");
KSYMTAB_FUNC(pm_svc_power_off, "", "");
KSYMTAB_FUNC(pm_svc_power_reset, "", "");
KSYMTAB_FUNC(pm_crg_svc_vote, "", "");
KSYMTAB_FUNC(pm_crg_enable_switch, "", "");
KSYMTAB_DATA(g_pm_board_info, "", "");
KSYMTAB_FUNC(pm_board_is_support_wkup_gpio, "", "");
KSYMTAB_FUNC(plat_register_reboot, "", "");
KSYMTAB_FUNC(plat_get_wifi_dfr_flag, "_gpl", "");
KSYMTAB_FUNC(wlan_set_dfr_recovery_flag, "_gpl", "");
KSYMTAB_FUNC(plat_wifi_exception_rst_register_etc, "_gpl", "");
KSYMTAB_FUNC(plat_bt_exception_rst_register_etc, "_gpl", "");
KSYMTAB_FUNC(plat_sle_exception_rst_register_etc, "_gpl", "");
KSYMTAB_FUNC(set_wlan_flag_close, "_gpl", "");
KSYMTAB_FUNC(plat_dfr_trigger_panic, "", "");
KSYMTAB_FUNC(wifi_driver_event_callback_register, "_gpl", "");
KSYMTAB_FUNC(plat_is_device_in_recovery, "", "");
KSYMTAB_FUNC(plat_update_device_recovery_flag, "", "");
KSYMTAB_FUNC(set_hcc_bus_close, "", "");
KSYMTAB_DATA(g_uc_custom_cali_done_etc, "_gpl", "");
KSYMTAB_DATA(g_wlan_pm_switch_etc, "_gpl", "");
KSYMTAB_DATA(g_wlan_fast_check_cnt, "_gpl", "");
KSYMTAB_FUNC(wlan_pm_get_drv_etc, "_gpl", "");
KSYMTAB_FUNC(wlan_pm_is_poweron_etc, "_gpl", "");
KSYMTAB_FUNC(wlan_pm_get_wifi_srv_handler_etc, "_gpl", "");
KSYMTAB_FUNC(wlan_cfg_init_cb_reg, "_gpl", "");
KSYMTAB_FUNC(wlan_open, "_gpl", "");
KSYMTAB_FUNC(wlan_open_ex, "_gpl", "");
KSYMTAB_FUNC(wlan_close, "_gpl", "");
KSYMTAB_FUNC(wlan_close_ex, "_gpl", "");
KSYMTAB_FUNC(pm_svc_open, "_gpl", "");
KSYMTAB_FUNC(pm_svc_close, "_gpl", "");
KSYMTAB_FUNC(pm_ble_open, "_gpl", "");
KSYMTAB_FUNC(pm_ble_close, "_gpl", "");
KSYMTAB_FUNC(pm_ble_enable, "_gpl", "");
KSYMTAB_FUNC(pm_ble_disable, "_gpl", "");
KSYMTAB_FUNC(pm_sle_open, "_gpl", "");
KSYMTAB_FUNC(pm_sle_close, "_gpl", "");
KSYMTAB_FUNC(pm_sle_enable, "_gpl", "");
KSYMTAB_FUNC(pm_sle_disable, "_gpl", "");
KSYMTAB_FUNC(pm_wifi_suspend_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_wifi_resume_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_ble_suspend_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_ble_resume_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_ble_enable_reply_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_sle_suspend_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_sle_resume_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_sle_enable_reply_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(pm_wifi_wkup_cb_host_register, "_gpl", "");
KSYMTAB_FUNC(GetHwSecureCVersion_ws73, "", "");
KSYMTAB_FUNC(snprintf_s_ws73, "", "");
KSYMTAB_FUNC(snprintf_truncated_s_ws73, "", "");
KSYMTAB_FUNC(sprintf_s_ws73, "", "");
KSYMTAB_FUNC(sscanf_s_ws73, "", "");
KSYMTAB_FUNC(strcat_s_ws73, "", "");
KSYMTAB_FUNC(strcpy_s_ws73, "", "");
KSYMTAB_FUNC(strncat_s_ws73, "", "");
KSYMTAB_FUNC(strncpy_s_ws73, "", "");
KSYMTAB_FUNC(strtok_s_ws73, "", "");
KSYMTAB_FUNC(uapi_tsensor_read_temperature, "", "");
KSYMTAB_FUNC(vsnprintf_s_ws73, "", "");
KSYMTAB_FUNC(vsnprintf_truncated_s_ws73, "", "");
KSYMTAB_FUNC(vsprintf_s_ws73, "", "");
KSYMTAB_FUNC(vsscanf_s_ws73, "", "");
KSYMTAB_FUNC(uapi_zdiag_psd_enable_register, "", "");
KSYMTAB_FUNC(uapi_zdiag_psd_enable_unregister, "", "");
KSYMTAB_FUNC(zdiag_log_print0_press_prv, "", "");
KSYMTAB_FUNC(zdiag_log_print1_press_prv, "", "");
KSYMTAB_FUNC(zdiag_log_print2_press_prv, "", "");
KSYMTAB_FUNC(zdiag_log_print3_press_prv, "", "");
KSYMTAB_FUNC(zdiag_log_print4_press_prv, "", "");
KSYMTAB_FUNC(zdiag_report_packet, "", "");

MODULE_INFO(depends, "");

MODULE_ALIAS("sdio:c*v*d3733*");
MODULE_ALIAS("sdio:c*v12D1d0073*");
