#ifndef WEB_PAGE_H_
#define WEB_PAGE_H_

static const char* WEB_PAGE_HTML =
    "<!DOCTYPE html>\n"
    "<html lang='zh-CN'><head><meta charset='utf-8'>\n"
    "<meta name='viewport' content='width=device-width, initial-scale=1'>\n"
    "<title>webrtc demo</title>\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0}\n"
    "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
    "background:#000;color:#fff;overflow:hidden;height:100vh;display:flex;"
    "flex-direction:column}\n"

    ".top-bar{background:rgba(26,29,35,.95);padding:0 1rem;height:40px;display:flex;"
    "align-items:center;justify-content:space-between;flex-shrink:0;z-index:10}\n"
    ".top-bar .brand{color:#fff;font-weight:600;font-size:.85rem;display:flex;"
    "align-items:center;gap:6px}\n"
    ".top-bar .brand-icon{width:22px;height:22px;background:#0d6efd;"
    "border-radius:5px;display:inline-flex;align-items:center;justify-content:center;"
    "font-size:13px}\n"
    ".top-bar .nav-info{color:#40c057;font-size:.7rem;font-weight:600;"
    "letter-spacing:.05em}\n"

    ".status-badge{display:inline-flex;align-items:center;gap:4px;padding:2px 10px;"
    "border-radius:20px;font-size:.7rem;font-weight:500}\n"
    ".status-badge.disconnected{background:rgba(255,255,255,.08);color:#868e96}\n"
    ".status-badge.connecting{background:#fff3bf;color:#e67700}\n"
    ".status-badge.connected{background:#d3f9d8;color:#2b8a3e}\n"
    ".status-badge.failed{background:#ffe3e3;color:#c92a2a}\n"
    ".status-dot{width:6px;height:6px;border-radius:50%;display:inline-block}\n"
    ".status-badge.disconnected .status-dot{background:#adb5bd}\n"
    ".status-badge.connecting .status-dot{background:#fab005}\n"
    ".status-badge.connected .status-dot{background:#40c057}\n"
    ".status-badge.failed .status-dot{background:#fa5252}\n"

    ".btn-conn{border:none;padding:4px 14px;border-radius:5px;font-size:.72rem;"
    "font-weight:500;cursor:pointer;transition:background .15s,opacity .15s}\n"
    ".btn-conn:disabled{opacity:.4;cursor:not-allowed}\n"
    ".btn-conn.connect{background:#0d6efd;color:#fff}\n"
    ".btn-conn.connect:hover{background:#0b5ed7}\n"
    ".btn-conn.disconnect{background:rgba(201,42,42,.85);color:#fff;display:none}\n"
    ".btn-conn.disconnect:hover{background:#a61e1e}\n"

    ".video-wrap{flex:1;position:relative;overflow:hidden;min-height:0;background:#000}\n"
    ".video-wrap video{width:100%;height:100%;object-fit:contain;display:block}\n"

    ".placeholder-msg{position:absolute;inset:0;display:flex;flex-direction:column;"
    "align-items:center;justify-content:center;color:#868e96;font-size:.85rem;z-index:1}\n"
    ".placeholder-msg .ph-icon{font-size:2.5rem;margin-bottom:10px;opacity:.5}\n"
    ".placeholder-msg .ph-text{opacity:.6}\n"

    ".video-controls{position:absolute;bottom:0;left:0;right:0;"
    "padding:8px 12px;background:linear-gradient(to top,rgba(0,0,0,.7),transparent);"
    "display:flex;align-items:center;gap:6px;opacity:0;transition:opacity .2s;z-index:5}\n"
    ".video-wrap:hover .video-controls{opacity:1}\n"
    ".ctrl-btn{background:rgba(255,255,255,.15);border:none;color:#fff;"
    "border-radius:4px;padding:6px 8px;cursor:pointer;display:inline-flex;"
    "align-items:center;gap:4px;transition:background .15s;line-height:1}\n"
    ".ctrl-btn:hover{background:rgba(255,255,255,.25)}\n"
    ".ctrl-btn:disabled{opacity:.4;cursor:not-allowed}\n"
    ".ctrl-btn svg{width:16px;height:16px;fill:currentColor;flex-shrink:0}\n"

    ".mdns-warn{position:fixed;top:0;left:0;right:0;background:#ff9800;"
    "color:#000;padding:8px 14px;z-index:9999;font-size:12px;line-height:1.4}\n"
    ".mdns-warn b{font-weight:700}\n"
    ".mdns-warn code{background:rgba(0,0,0,.1);padding:1px 4px;border-radius:3px;"
    "font-size:.85em}\n"
    ".mdns-warn button{margin-left:10px;background:#000;color:#fff;border:none;"
    "padding:3px 10px;border-radius:4px;cursor:pointer;font-size:.8em}\n"

    "@media(max-width:767px){\n"
    "  .top-bar{padding:0 .75rem;padding-top:max(0px,env(safe-area-inset-top));height:36px}\n"
    "  .top-bar .brand{font-size:.8rem}\n"
    "  .video-controls{opacity:1;padding:6px 8px;gap:4px}\n"
    "  .ctrl-btn{padding:5px 7px}\n"
    "  .ctrl-btn svg{width:14px;height:14px}\n"
    "  .btn-conn{min-height:28px;"
    "-webkit-tap-highlight-color:transparent;touch-action:manipulation}\n"
    "}\n"
    "</style></head><body>\n"

    "<div class='top-bar'>\n"
    "  <div class='brand'>\n"
    "    <span class='brand-icon'><svg viewBox='0 0 24 24' width='14' height='14' fill='#fff'><path d='M17 10.5V7c0-.55-.45-1-1-1H4c-.55 0-1 .45-1 1v10c0 .55.45 1 1 1h12c.55 0 1-.45 1-1v-3.5l4 4v-11l-4 4z'/></svg></span>\n"
    "    webrtc demo\n"
    "  </div>\n"
    "  <span class='status-badge disconnected' id='status-badge'>\n"
    "    <span class='status-dot'></span>\n"
    "    <span id='status-text'>Disconnected</span>\n"
    "  </span>\n"
    "  <span class='nav-info' id='nav-info'></span>\n"
    "  <button class='btn-conn connect' id='btn' onclick='doConnect()'>Connect</button>\n"
    "  <button class='btn-conn disconnect' id='btn-disconnect' onclick='doDisconnect()'>Disconnect</button>\n"
    "</div>\n"

    "<div class='video-wrap'>\n"
    "  <video id='video' autoplay playsinline muted></video>\n"
    "  <div id='view-notconnected' class='placeholder-msg'>\n"
    "    <div class='ph-icon'><svg viewBox='0 0 24 24' width='48' height='48' fill='#868e96'><path d='M17 10.5V7c0-.55-.45-1-1-1H4c-.55 0-1 .45-1 1v10c0 .55.45 1 1 1h12c.55 0 1-.45 1-1v-3.5l4 4v-11l-4 4z'/></svg></div>\n"
    "    <div class='ph-text'>Click Connect to start preview</div>\n"
    "  </div>\n"
    "  <div class='video-controls'>\n"
    "    <button class='ctrl-btn' id='ctrl-screenshot' title='Screenshot' onclick='doScreenshot()'>\n"
    "      <svg viewBox='0 0 24 24'><path d='M12 15.2a3.2 3.2 0 1 0 0-6.4 3.2 3.2 0 0 0 0 6.4z'/><path d='M9 2L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2h-3.17L15 2H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z'/></svg>\n"
    "    </button>\n"
    "    <div style='flex:1'></div>\n"
    "    <button class='ctrl-btn' id='ctrl-fullscreen' title='Fullscreen' onclick='toggleFullscreen()'>\n"
    "      <svg viewBox='0 0 24 24'><path d='M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z'/></svg>\n"
    "    </button>\n"
    "  </div>\n"
    "</div>\n"

    "<script>\n"
    "var pc=null,localIP='';\n"

    "function setStatus(state){\n"
    "  var badge=document.getElementById('status-badge');\n"
    "  var text=document.getElementById('status-text');\n"
    "  text.textContent=state;\n"
    "  badge.className='status-badge';\n"
    "  if(state==='connected'||state==='completed'){badge.classList.add('connected')}\n"
    "  else if(state==='connecting'||state==='checking'||state==='new'){badge.classList.add('connecting')}\n"
    "  else if(state==='failed'){badge.classList.add('failed')}\n"
    "  else{badge.classList.add('disconnected')}\n"
    "}\n"

    "function fixMdnsSDP(sdp){\n"
    "  if(!localIP||sdp.indexOf('.local')===-1)return sdp;\n"
    "  return sdp.replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\.local/g,localIP);\n"
    "}\n"

    "async function doConnect(){\n"
    "  if(pc){pc.close();pc=null}\n"
    "  var btn=document.getElementById('btn');\n"
    "  btn.disabled=true;\n"
    "  document.getElementById('btn-disconnect').style.display='none';\n"
    "  setStatus('connecting');\n"
    "  localIP=window.location.hostname;\n"
    "  pc=new RTCPeerConnection({iceServers:[]});\n"

    "  pc.onicecandidate=function(e){\n"
    "    if(!e.candidate)return;\n"
    "    var parts=e.candidate.candidate.split(' ');\n"
    "    if(parts.length>4&&parts[4]&&!parts[4].includes('.local')){\n"
    "      localIP=parts[4];\n"
    "    }\n"
    "    if(e.candidate.candidate&&e.candidate.candidate.includes('.local')){\n"
    "      showMdnsWarning();\n"
    "    }\n"
    "  };\n"

    "  pc.ontrack=function(ev){\n"
    "    var ms=new MediaStream();\n"
    "    ms.addTrack(ev.track);\n"
    "    if(ev.track.kind==='video'){\n"
    "      document.getElementById('video').srcObject=ms;\n"
    "      document.getElementById('view-notconnected').style.display='none';\n"
    "    }\n"
    "  };\n"

    "  pc.oniceconnectionstatechange=function(){\n"
    "    var s=pc.iceConnectionState;\n"
    "    setStatus(s);\n"
    "    if(s==='connected'||s==='completed'){\n"
    "      document.getElementById('btn').style.display='none';\n"
    "      document.getElementById('btn-disconnect').style.display='inline-block';\n"
    "      document.getElementById('nav-info').textContent='LIVE';\n"
    "    }else if(s==='disconnected'||s==='closed'||s==='failed'){\n"
    "      onDisconnected();\n"
    "    }\n"
    "  };\n"

    "  try{\n"
    "    var resp=await fetch('/offer');\n"
    "    if(!resp.ok){setStatus('failed');btn.disabled=false;return}\n"
    "    var offerSDP=await resp.text();\n"
    "    await pc.setRemoteDescription({type:'offer',sdp:offerSDP});\n"
    "    var answer=await pc.createAnswer();\n"
    "    await pc.setLocalDescription(answer);\n"
    "    await new Promise(function(r){\n"
    "      if(pc.iceGatheringState==='complete')r();\n"
    "      else{pc.onicegatheringstatechange=function(){\n"
    "if(pc.iceGatheringState==='complete')r()};\n"
    "      setTimeout(r,3000);}\n"
    "    });\n"
    "    var fixedSDP=fixMdnsSDP(pc.localDescription.sdp);\n"
    "    await fetch('/answer',{method:'POST',"
    "headers:{'Content-Type':'application/sdp'},"
    "body:fixedSDP});\n"
    "  }catch(e){setStatus('failed')}\n"
    "  btn.disabled=false;\n"
    "}\n"

    "function doDisconnect(){\n"
    "  if(pc){pc.close();pc=null}\n"
    "  onDisconnected();\n"
    "}\n"

    "function onDisconnected(){\n"
    "  document.getElementById('btn').style.display='inline-block';\n"
    "  document.getElementById('btn').disabled=false;\n"
    "  document.getElementById('btn-disconnect').style.display='none';\n"
    "  document.getElementById('view-notconnected').style.display='flex';\n"
    "  document.getElementById('video').srcObject=null;\n"
    "  document.getElementById('nav-info').textContent='';\n"
    "  setStatus('disconnected');\n"
    "}\n"

    "function doScreenshot(){\n"
    "  var v=document.getElementById('video');\n"
    "  if(!v.srcObject)return;\n"
    "  var c=document.createElement('canvas');\n"
    "  c.width=v.videoWidth||640;c.height=v.videoHeight||480;\n"
    "  c.getContext('2d').drawImage(v,0,0,c.width,c.height);\n"
    "  var a=document.createElement('a');\n"
    "  a.href=c.toDataURL('image/jpeg',0.95);\n"
    "  a.download='screenshot_'+Date.now()+'.jpg';\n"
    "  a.click();\n"
    "}\n"

    "function toggleFullscreen(){\n"
    "  var w=document.querySelector('.video-wrap');\n"
    "  if(!w)return;\n"
    "  if(!document.fullscreenElement){w.requestFullscreen().catch(function(){})}\n"
    "  else{document.exitFullscreen()}\n"
    "}\n"

    "var mdnsWarnShown=false;\n"
    "function showMdnsWarning(){\n"
    "  if(mdnsWarnShown)return;mdnsWarnShown=true;\n"
    "  var w=document.createElement('div');\n"
    "  w.className='mdns-warn';\n"
    "  w.innerHTML='<b>mDNS privacy detected!</b> Local IPs are hidden with .local names. "
    "Fix: Chrome/Edge: open <code>*://flags/#enable-webrtc-hide-local-ips-with-mdns</code> "
    "and set to <b>Disabled</b>, then restart. "
    "Or launch with: <code>--disable-features=WebRtcHideLocalIpsWithMdns</code>. "
    "Firefox: no action needed. "
    "<button onclick=\"this.parentElement.remove()\">Dismiss</button>';\n"
    "  document.body.appendChild(w);\n"
    "}\n"
    "</script></body></html>";

#endif
