/*
 * Copyright (c) CompanyNameMagicTag 2023-2023. All rights reserved.
 * Description: plat hcc msg type.
 * Author: AuthorNameMagicTag
 * Create: 2023-6-29
 */

#ifndef __PLAT_HCC_MSG_TYPE_H__
#define __PLAT_HCC_MSG_TYPE_H__

typedef enum _plat_cfg_h2d_msg_type {
    H2D_PLAT_CFG_MSG_BEGIN = 0,
    H2D_PLAT_CFG_MSG_PM_INI = H2D_PLAT_CFG_MSG_BEGIN,
    H2D_PLAT_CFG_MSG_DFR_INI,
    H2D_PLAT_CFG_MSG_PM_CRG_VOTE,
    H2D_PLAT_CFG_MSG_SLP_EN,
    H2D_PLAT_CFG_MSG_SLP_UART_BAUD_SET,
    H2D_PLAT_CFG_MSG_SEND_TRNG,
    H2D_PLAT_CFG_MSG_TRIGGER_PANIC,
    H2D_PLAT_CFG_MSG_COEX_GATEWAY_TO_BSLE,
    H2D_PLAT_CFG_MSG_XO_TRIM_TEMP_INI,
    H2D_PLAT_CFG_MSG_UPDATE_XO_TRIM,
    H2D_PLAT_CFG_MSG_WRITE_EFUSE,
    H2D_PLAT_CFG_MSG_READ_EFUSE,
    H2D_PLAT_CFG_MSG_GPIO_TEST,
    H2D_PLAT_CFG_MSG_GET_VERSION,
    H2D_PLAT_CFG_MSG_GET_UNIQUE_CODE,
    H2D_PLAT_CFG_MSG_GET_TEMP,
    H2D_PLAT_CFG_MSG_GET_CHIP_TYPE,
    H2D_PLAT_CFG_MSG_END
} plat_cfg_h2d_msg_type;

typedef enum _plat_cfg_d2h_msg_type {
    D2H_PLAT_CFG_MSG_BEGIN = 0,
    D2H_PLAT_CFG_MSG_SEND_TRNG = D2H_PLAT_CFG_MSG_BEGIN,
    D2H_PLAT_CFG_MSG_SLP_EN_COMPLETE,
    D2H_SLP_UART_BAUD_SET_COMPLETE,
    D2H_PLAT_CFG_MSG_COEX_BSLE_TO_GATEWAY,
    D2H_PLAT_CFG_MSG_WRITE_EFUSE_COMPLETE,
    D2H_PLAT_CFG_MSG_READ_EFUSE_COMPLETE,
    D2H_PLAT_CFG_MSG_GPIO_TEST_COMPLETE,
    D2H_PLAT_CFG_MSG_GET_VERSION_COMPLETE,
    D2H_PLAT_CFG_MSG_GET_UNIQUE_CODE,
    D2H_PLAT_CFG_MSG_GET_TEMP,
    D2H_PLAT_CFG_MSG_GET_CHIP_TYPE_COMPLETE,
    D2H_PLAT_CFG_MSG_END
} plat_cfg_d2h_msg_type;

#endif
