/*
 * Copyright (c) CompanyNameMagicTag 2022-2022. All rights reserved.
 * Description: 校准涉及到的phy寄存器操作接口
 * Date: 2022-10-22
 */

#ifndef __FE_HAL_PHY_REG_IF_HOST_H__
#define __FE_HAL_PHY_REG_IF_HOST_H__

#include "osal_types.h"
#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif
#ifdef _PRE_WLAN_ONLINE_CALI
// 动态功率
osal_void hal_set_dyn_tx_power_cali_dyn_tx_power_cali(osal_u32 xFthwLPwuiTW_w6GoB_);
osal_void hal_set_tx_power_accum_delay_power_accum_delay(osal_u32 xGvqmwOzCCSIO4mxzQ_);
osal_void hal_set_cali_new_add_reg_cfg_fb_pwr_calc_prd(osal_u32 xCt2OtyOGqwOCzxCOGw4_);
#endif
// TPC ram 读写
#if !(defined(_PRE_WLAN_ATE) || defined(_PRE_WIFI_EDA))
osal_void hal_set_tpc_ram_access_reg1_cfg_tpc_ram_period(osal_u32 xCt2ORGCOwzIOGmwlv4_);
osal_void hal_set_tpc_ram_access_reg1_cfg_indirect_rw_mode(osal_u32 x6NgwBhFB_W6Lw_TwSiFW_);
osal_void hal_set_tpc_ram_access_reg1_cfg_tpc_table_access_addr(osal_u32 xCt2ORGCORzyxmOzCCmssOz44w_);
#endif
osal_void hal_set_tpc_ram_access_reg2_cfg_tpc_table_wr_data(osal_u32 x6NgwLu6wLGjoWwT_wFGLG_);
// 二级映射
osal_void hal_set_rf_ppa_code_lut0_cfg_rf_ppa_code_lut0(osal_u32 xCt2OwtOGGzOCv4mOxSR3_);
osal_u32 hal_get_rf_ppa_code_lut0_cfg_rf_ppa_code_lut0(osal_void);
osal_void hal_set_rf_ppa_code_lut0_cfg_rf_ppa_code_lut1(osal_u32 x6Ngw_NwuuGw6iFWwodL0_);
osal_u32 hal_get_rf_ppa_code_lut0_cfg_rf_ppa_code_lut1(osal_void);
osal_void hal_set_rf_ppa_code_lut1_cfg_rf_ppa_code_lut2(osal_u32 xCt2OwtOGGzOCv4mOxSRZ_);
osal_u32 hal_get_rf_ppa_code_lut1_cfg_rf_ppa_code_lut2(osal_void);
osal_void hal_set_rf_ppa_code_lut1_cfg_rf_ppa_code_lut3(osal_u32 xCt2OwtOGGzOCv4mOxSRi_);
osal_u32 hal_get_rf_ppa_code_lut1_cfg_rf_ppa_code_lut3(osal_void);
osal_void hal_set_rf_ppa_code_lut2_cfg_rf_ppa_code_lut4(osal_u32 x6Ngw_NwuuGw6iFWwodLD_);
osal_u32 hal_get_rf_ppa_code_lut2_cfg_rf_ppa_code_lut4(osal_void);
osal_void hal_set_rf_ppa_code_lut2_cfg_rf_ppa_code_lut5(osal_u32 xCt2OwtOGGzOCv4mOxSRa_);
osal_u32 hal_get_rf_ppa_code_lut2_cfg_rf_ppa_code_lut5(osal_void);
osal_void hal_set_rf_ppa_code_lut3_cfg_rf_ppa_code_lut6(osal_u32 x6Ngw_NwuuGw6iFWwodLX_);
osal_u32 hal_get_rf_ppa_code_lut3_cfg_rf_ppa_code_lut6(osal_void);
osal_void hal_set_rf_ppa_code_lut3_cfg_rf_ppa_code_lut7(osal_u32 xCt2OwtOGGzOCv4mOxSR9_);
osal_u32 hal_get_rf_ppa_code_lut3_cfg_rf_ppa_code_lut7(osal_void);
osal_void hal_set_rf_ppa_code_lut4_cfg_rf_ppa_code_lut8(osal_u32 x6Ngw_NwuuGw6iFWwodLU_);
osal_u32 hal_get_rf_ppa_code_lut4_cfg_rf_ppa_code_lut8(osal_void);
osal_void hal_set_rf_ppa_code_lut4_cfg_rf_ppa_code_lut9(osal_u32 xCt2OwtOGGzOCv4mOxSRc_);
osal_u32 hal_get_rf_ppa_code_lut4_cfg_rf_ppa_code_lut9(osal_void);
osal_void hal_set_rf_ppa_code_lut5_cfg_rf_ppa_code_lut10(osal_u32 xCt2OwtOGGzOCv4mOxSRr3_);
osal_u32 hal_get_rf_ppa_code_lut5_cfg_rf_ppa_code_lut10(osal_void);
osal_void hal_set_rf_pa_code_lut0_cfg_rf_pa_code_lut0(osal_u32 xCt2OwtOGzOCv4mOxSR3_);
osal_void hal_set_rf_pa_code_lut0_cfg_rf_pa_code_lut1(osal_u32 x6Ngw_NwuGw6iFWwodL0_);
osal_void hal_set_rf_pa_code_lut0_cfg_rf_pa_code_lut2(osal_u32 xCt2OwtOGzOCv4mOxSRZ_);
osal_void hal_set_rf_pa_code_lut0_cfg_rf_pa_code_lut3(osal_u32 xCt2OwtOGzOCv4mOxSRi_);
osal_void hal_set_rf_pa_code_lut1_cfg_rf_pa_code_lut4(osal_u32 x6Ngw_NwuGw6iFWwodLD_);
osal_void hal_set_rf_pa_code_lut1_cfg_rf_pa_code_lut5(osal_u32 xCt2OwtOGzOCv4mOxSRa_);
osal_void hal_set_rf_pa_code_lut1_cfg_rf_pa_code_lut6(osal_u32 x6Ngw_NwuGw6iFWwodLX_);
osal_void hal_set_rf_pa_code_lut1_cfg_rf_pa_code_lut7(osal_u32 xCt2OwtOGzOCv4mOxSR9_);
osal_void hal_set_rf_pa_code_lut2_cfg_rf_pa_code_lut8(osal_u32 x6Ngw_NwuGw6iFWwodLU_);
osal_void hal_set_rf_pa_code_lut2_cfg_rf_pa_code_lut9(osal_u32 xCt2OwtOGzOCv4mOxSRc_);
osal_void hal_set_rf_pa_code_lut2_cfg_rf_pa_code_lut10(osal_u32 xCt2OwtOGzOCv4mOxSRr3_);
osal_void hal_set_rf_pa_code_lut2_cfg_rf_pa_code_lut11(osal_u32 x6Ngw_NwuGw6iFWwodL00_);
osal_void hal_set_rf_pa_code_lut3_cfg_rf_pa_code_lut12(osal_u32 xCt2OwtOGzOCv4mOxSRrZ_);
osal_void hal_set_rf_pa_code_lut3_cfg_rf_pa_code_lut13(osal_u32 xCt2OwtOGzOCv4mOxSRri_);
osal_void hal_set_rf_pa_code_lut3_cfg_rf_pa_code_lut14(osal_u32 x6Ngw_NwuGw6iFWwodL0D_);
osal_void hal_set_rf_pa_code_lut3_cfg_rf_pa_code_lut15(osal_u32 xCt2OwtOGzOCv4mOxSRra_);
// dbb sacle shadow
osal_void hal_set_tpc_boundary_threshold1_cfg_tpc_boundary_0(osal_u32 x6NgwLu6wjidhFG_twy_);
osal_void hal_set_tpc_boundary_threshold1_cfg_tpc_boundary_1(osal_u32 xCt2ORGCOyvSo4zwQOr_);
osal_void hal_set_tpc_boundary_threshold1_cfg_tpc_boundary_2(osal_u32 x6NgwLu6wjidhFG_twV_);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_3(osal_u32 x6NgwLu6wjidhFG_twk_);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_4(osal_u32 xCt2ORGCOyvSo4zwQOK_);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_5(osal_u32 x6NgwLu6wjidhFG_twx_);
osal_void hal_set_tpc_boundary_threshold2_cfg_tpc_boundary_6(osal_u32 xCt2ORGCOyvSo4zwQOY_);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_0(osal_u32 x6NgwFjjwC6GoWwCQGFiTwy_);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_0(osal_void);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_1(osal_u32 xCt2O4yyOsCzxmOsAz4vqOr_);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_1(osal_void);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_2(osal_u32 x6NgwFjjwC6GoWwCQGFiTwV_);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_2(osal_void);
osal_void hal_set_dbb_scale_shadow1_cfg_dbb_scale_shadow_3(osal_u32 x6NgwFjjwC6GoWwCQGFiTwk_);
osal_u32 hal_get_dbb_scale_shadow1_cfg_dbb_scale_shadow_3(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_4(osal_u32 xCt2O4yyOsCzxmOsAz4vqOK_);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_4(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_5(osal_u32 x6NgwFjjwC6GoWwCQGFiTwx_);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_5(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_6(osal_u32 xCt2O4yyOsCzxmOsAz4vqOY_);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_6(osal_void);
osal_void hal_set_dbb_scale_shadow2_cfg_dbb_scale_shadow_7(osal_u32 x6NgwFjjwC6GoWwCQGFiTwp_);
osal_u32 hal_get_dbb_scale_shadow2_cfg_dbb_scale_shadow_7(osal_void);
osal_void hal_set_cfg_reserv_1_reg_1_reserv_1_wr_addr(osal_u32 x_WCW_qw0wT_wGFF__);
osal_void hal_set_cfg_reserv_1_reg_1_cfg_reserv_1_wr_en(osal_u32 xCt2OwmsmwPOrOqwOmo_);
osal_void hal_set_cfg_reserv_1_reg_2_reserv_1_wr_value_0ch(osal_u32 x_WCW_qw0wT_wqGodWwy6Q_);
osal_u32 hal_get_he_tx_foc_power_boost_win_ctrl_cfg_tx_power_boost_bypass(osal_void);
#ifdef _PRE_WLAN_FEATURE_DAQ
osal_void hal_set_sample_cfg_2_cfg_debug_sample_by_len(osal_u32 x6NgwFWjdgwCGSuoWwjtwoWh_);
osal_void hal_set_sample_cfg_0_cfg_debug_sample_end_mode(osal_u32 cfg_debug_sample_end_mode);
osal_void hal_set_sample_cfg_0_cfg_debug_sample_start_mode(osal_u32 cfg_debug_sample_start_mode);
osal_void hal_set_sample_cfg_2_cfg_with_sample_delay_en(osal_u32 cfg_with_sample_delay_en);
osal_void hal_set_sample_cfg_2_cfg_debug_sample_delay(osal_u32 cfg_debug_sample_delay);
osal_void hal_set_sample_cfg_2_cfg_with_mac_tsf_en(osal_u32 cfg_with_mac_tsf_en);
osal_void hal_set_sample_cfg_2_cfg_with_mac_info_en(osal_u32 cfg_with_mac_info_en);
osal_void hal_set_sample_cfg_0_cfg_debug_sample_en(osal_u32 xCt2O4myS2OszIGxmOmo_);
osal_void hal_set_wlbb_clr_sample_clear_sample_done(osal_u32 xCxmzwOszIGxmO4vom_);
osal_void hal_set_sample_cfg_0_cfg_phy_data_sample_cg_bps(osal_u32 x6NgwuQtwFGLGwCGSuoWw6gwjuC_);
osal_void hal_set_sample_cfg_0_cfg_phy_data_sample_clk_en(osal_u32 x6NgwuQtwFGLGwCGSuoWw6oKwWh_);
#endif
#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif  // __CALI_PHY_REG_IF_H__