from setuptools import setup, Extension, find_packages
import pybind11
import os

# Get LVGL include and lib paths from environment or use defaults
staging_dir = os.environ.get('STAGING_DIR', '')
lvgl_include = os.path.join(staging_dir, 'usr', 'include') if staging_dir else '/usr/include'
lvgl_lib_dir = os.path.join(staging_dir, 'usr', 'lib') if staging_dir else '/usr/lib'

# Pre-generated LVGL binding source (generated by gen_pybind11.py offline)
lvgl_generated_src = os.path.join(os.path.dirname(__file__), 'lvgl', 'lvgl_pybind_generated.cpp')

ext = Extension(
    "k230_ext",
    sources=["k230_c_ext/_ext.c"],
)

k230_display = Extension(
    "k230_display",
    sources=["k230_display/k230_display_pybind.cpp","k230_display/k230_display_pybind_display_lib.cpp"],
    include_dirs=[pybind11.get_include()],
    libraries=["display", "drm", "opencv_core", "opencv_imgproc"],
    extra_compile_args=["-O3", "-mcpu=c908v", "-mabi=lp64d", "-mtune=c908", "-mrvv-v0p10-compatible", "-mrvv-auto-vectorize", "-std=c++17"],
    language='c++',
)

k230_v4l2_drm = Extension(
    "k230_v4l2_drm",
    sources=[
        "k230_v4l2/k230_v4l2_drm_pybind.cpp",
        "k230_v4l2/k230_osd.cpp",
        "k230_v4l2/v4l2_drm.cpp",
    ],
    include_dirs=[pybind11.get_include()],
    libraries=["v4l2-drm", "display", "drm"],
    extra_compile_args=["-O3", "-mcpu=c908v", "-mabi=lp64d", "-mtune=c908", "-mrvv-v0p10-compatible", "-mrvv-auto-vectorize", "-std=c++17"],
    language='c++',
)

# LVGL Python binding extension
# The source file lvgl_pybind_generated.cpp is pre-generated by gen_pybind11.py
# To regenerate: python3 lvgl/gen_pybind11.py -M lvgl -MP lv -I <lvgl_include> -I <lv_conf_dir> -I <fake_libc> -o lvgl/lvgl_pybind_generated.cpp <lvgl.h>
lvgl_ext = Extension(
    "lvgl._lvgl",
    sources=[lvgl_generated_src],
    include_dirs=[
        pybind11.get_include(),
        lvgl_include,
        os.path.join(lvgl_include, 'lvgl'),
        os.path.join(lvgl_include, 'lvgl_private'),
        os.path.join(os.path.dirname(__file__), 'lvgl'),  # for lvgl_pybind_helpers.h
    ],
    library_dirs=[lvgl_lib_dir],
    libraries=["lvgl", "lvgl_linux", "drm", "evdev", "m", "pthread"],
    extra_compile_args=[
        "-O3",
        "-mcpu=c908v",
        "-mabi=lp64d",
        "-mtune=c908",
        "-mrvv-v0p10-compatible",
        "-mrvv-auto-vectorize",
        "-std=c++17",
        "-Wno-deprecated-declarations",
        "-Wno-unused-function",
        "-DLV_CONF_PATH=\"lv_conf.h\"",
    ],
    extra_link_args=[
        "-Wl,-rpath,/usr/lib",
    ],
    language='c++',
)

setup(
    name="k230-python",
    version="1.0.0",
    author="wangjianxin",
    description="Python for k230",
    packages=find_packages(),
    ext_modules=[ext, k230_display, k230_v4l2_drm, lvgl_ext],
    zip_safe=False,
    entry_points={
        "console_scripts": [
            "k230-iomux=k230.iomux:main",
        ],
    },
)
