/*
 * Copyright (c) CompanyNameMagicTag 2021-2023. All rights reserved.
 * Description: Header file of hmac&dmac message id defined.
 * Create: 2021-06-16
 */

#ifndef WLAN_MSG_ROM_H
#define WLAN_MSG_ROM_H
typedef enum {
    EN_WLAN_MSG_BEGIN = 0,
    WLAN_MSG_D2H_C_BEGIN = EN_WLAN_MSG_BEGIN,
    WLAN_MSG_D2H_C_DEL_BA = WLAN_MSG_D2H_C_BEGIN,
    WLAN_MSG_D2H_C_ALG_INFO_SYN,
    WLAN_MSG_D2H_C_ALG_DISTANCE_SYN,
    WLAN_MSG_D2H_C_VOICE_AGGR,
    WLAN_MSG_D2H_C_DBAC,
    WLAN_MSG_D2H_C_SYNC_HOST,
    WLAN_MSG_D2H_C_DEV_READY_FOR_HOST_SLP,
    WLAN_MSG_D2H_C_CFG_CFG80211_MGMT_TX_STATUS,
    WLAN_MSG_D2H_C_CFG_SYNC_TWT_STATUS,
    WLAN_MSG_D2H_C_CFG_DEL_VAP_SUCCESS,
    WLAN_MSG_D2H_C_CFG_DFR,
    WLAN_MSG_D2H_C_P2P_CT_WINDOW_INFO,
    WLAN_MSG_D2H_C_CFG_RX_CSI,
    WLAN_MSG_D2H_CRX_RPT_HE_ROM,
    WLAN_MSG_D2H_C_RX_DSCR_RECV,
    WLAN_MSG_D2H_AL_TX,
    WLAN_MSG_D2H_TBTT,
    WLAN_MSG_D2H_CH_STATICS_COMP,
    WLAN_MSG_D2H_ANTI_INTF_SWITCH,
    WLAN_MSG_D2H_BT_ABORT_END,
    WLAN_MSG_D2H_RADAR_DETECTED,
    WLAN_MSG_D2H_BT_STATUS_CHANGE,
    WLAN_MSG_D2H_DPD_TO_HMAC,
    WLAN_MSG_D2H_CALI_TO_HMAC,
    WLAN_MSG_D2H_BCN_NO_FRM,
    WLAN_MSG_D2H_WUR_SP_START,
    WLAN_MSG_D2H_WUR_SP_END,
    WLAN_MSG_D2H_MISS_BEACON,
    WLAN_MSG_D2H_C_CUSTOM_CFG_PRIV_INI,
    WLAN_MSG_D2H_C_CFG_TX_COMP_SCHEDULE,
    WLAN_MSG_D2H_CRX_PS_TX_STATUS,
    WLAN_MSG_D2H_SEND_FTM_COMPLETE,
    WLAN_MSG_D2H_C_CFG_CFG80211_DATA_TX_STATUS,
    WLAN_MSG_D2H_C_CFG_KEEPALIVE_SYNC_TIMESTAMP,
    WLAN_MSG_D2H_C_CFG_SET_P2P_NOA,
    WLAN_MSG_D2H_C_CFG_SET_BEACON_PERIOD,
    WLAN_MSG_D2H_C_CFG_SYNC_PSM_STATUS,
    WLAN_MSG_D2H_ALG_SCHEDULE_STAT_INFO,
    WLAN_MSG_D2H_PSD_DATA_REPORT,
    WLAN_MSG_D2H_DYNAMIC_WOW_RESULT_INFO,
    WLAN_MSG_D2H_ANTI_INTF_INFO_REPORT,
    WLAN_MSG_D2H_WOW_OFFLOAD_PARAM_SYNC,
    WLAN_MSG_D2H_TX_COMPLETE_ONLINE_RF_CALI,
    WLAN_MSG_D2H_C_CFG_CHBA_MSG,
    WLAN_MSG_D2H_OFFLINE_CALI_FINISH,
    WLAN_MSG_D2H_C_END
} wlan_msg_d2h_c_enum;

typedef enum {
    WLAN_MSG_D2H_M_BEGIN = WLAN_MSG_D2H_C_END,
    WLAN_MSG_D2H_M_END
} wlan_msg_d2h_m_enum;

typedef enum {
    WLAN_MSG_D2H_D_BEGIN = WLAN_MSG_D2H_M_END,
    WLAN_MSG_D2H_D_END
} wlan_msg_d2h_d_enum;
typedef enum {
    WLAN_MSG_D2D_BEGIN = WLAN_MSG_D2H_D_END,
    WLAN_MSG_D2D_BT_STATUS_CHANGE = WLAN_MSG_D2D_BEGIN,
    WLAN_MSG_D2D_INTR_TX_QUEUE_AL_EMPTY,
    WLAN_MSG_D2D_CRX_RX,
    WLAN_MSG_D2D_CRX_FTM_ACK_COMPLETE,
    WLAN_MSG_D2D_RX,
    WLAN_MSG_D2D_TX,
    WLAN_MSG_D2D_TBTT,
    WLAN_MSG_D2D_FRW_TIMEOUT,
    WLAN_MSG_D2D_CH_STATICS_COMP_INTF,
    WLAN_MSG_D2D_P2P_NOA_ABSENT_START,
    WLAN_MSG_D2D_P2P_NOA_ABSENT_END,
    WLAN_MSG_D2D_P2P_CTWINDOW_END,
    WLAN_MSG_D2D_BEACON_TIMEOUT,
    WLAN_MSG_D2D_BCN_NO_FRM,
    WLAN_MSG_D2D_IRQ_MAC_ERROR,
    WLAN_MSG_D2D_SMOOTH_PHASE,
    WLAN_MSG_D2D_TWT_SP_START,
    WLAN_MSG_D2D_TWT_SP_END,
    WLAN_MSG_D2D_NETBUF_TX,
    WLAN_MSG_D2D_CSI_RX_COMPLETE,
    WLAN_MSG_D2D_DBAC_FCS,
    WLAN_MSG_D2D_SDP_PEROID_TIMER,
    WLAN_MSG_D2D_SDP_DW_TIMER,
    WLAN_MSG_D2D_CRX_RPT_TRIG_PARA,
    WLAN_MSG_D2D_C_CFG_RX_CSI,
    WLAN_MSG_D2D_BT_ABORT_END,
#ifdef _PRE_WLAN_FEATURE_FRW_IPC
    WLAN_MSG_D2D_H2D_NETBUF,
    WLAN_MSG_D2D_H2D_MSG,
    WLAN_MSG_D2D_H2D_CUSTOMIZE,
#endif
    WLAN_MSG_D2D_END
} wlan_msg_d2d_enum;

#endif
