#!/bin/bash
set -xe
# Environment: Install Ubuntu 24.04 in local VMware, then execute this script
#sudo mount -o remount,exec,dev rpool/USERDATA/home_hlhzl3  /home
sudo rm -rf ubuntu24
sudo apt install -y qemu-user-static binfmt-support debootstrap debian-ports-archive-keyring systemd-container rsync wget

sudo debootstrap --arch=riscv64   noble ubuntu24 https://mirrors.aliyun.com/ubuntu-ports/
sudo chroot ubuntu24 /bin/bash << 'EOFF'

cat >/etc/apt/sources.list <<EOF
deb https://mirrors.aliyun.com/ubuntu-ports noble main restricted

deb https://mirrors.aliyun.com/ubuntu-ports noble-updates main restricted

deb https://mirrors.aliyun.com/ubuntu-ports noble universe
deb https://mirrors.aliyun.com/ubuntu-ports noble-updates universe

deb https://mirrors.aliyun.com/ubuntu-ports noble multiverse
deb https://mirrors.aliyun.com/ubuntu-ports noble-updates multiverse

deb https://mirrors.aliyun.com/ubuntu-ports noble-backports main restricted universe multiverse

deb https://mirrors.aliyun.com/ubuntu-ports noble-security main restricted
deb https://mirrors.aliyun.com/ubuntu-ports noble-security universe
deb https://mirrors.aliyun.com/ubuntu-ports noble-security multiverse
EOF

echo "root:root" | chpasswd
echo k230>/etc/hostname
mount -t devpts devpts /dev/pts
mount -t proc proc /proc
apt-get update

#-------locales
apt install  -y   locales
sed -i 's/^#\s*\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
locale-gen
cat > /etc/default/locale <<EOF
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
EOF
#-------locales end

#-------ssh
apt install  -y     openssh-server
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
systemctl enable  ssh
#-------ssh end

#-------auto ntpdate
apt install  -y systemd-timesyncd
rm -rf /etc/localtime; ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;
sed -i -E 's/^#?NTP=.*$/NTP=cn.pool.ntp.org ntp.ntsc.ac.cn  /' /etc/systemd/timesyncd.conf
sed -i -E 's/^#?FallbackNTP=.*$/FallbackNTP=ntp.aliyun.com 0.debian.pool.ntp.org/' /etc/systemd/timesyncd.conf
systemctl enable  systemd-timesyncd
#-------auto ntpdate end


#-------wifi
apt install -y wpasupplicant
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 8.8.4.4" >> /etc/resolv.conf
#-------wifi end

#-------mount boot part,resize sd part
apt install -y parted libmxml-dev
cat << 'EOF' > /opt/mount_boot.sh
#!/bin/bash
bootddev=$(cat /proc/cmdline  | sed  -n  "s#root=\(\/dev\/mmcblk[0-9]\).*#\1#p" )
echo -e "Fix\n" | parted ---pretend-input-tty ${bootddev} print
sd_size=$(parted ${bootddev} print | grep ${bootddev} | cut -d: -f2)
parted ${bootddev} resizepart 2 ${sd_size}; resize2fs ${bootddev}p2
mount ${bootddev}p1 /boot
EOF
chmod a+x /opt/mount_boot.sh
cat >/etc/systemd/system/mount_boot.service <<EOF
# Generated by AI: Debian system auto-run script via systemd
[Unit]
Description=mount_boot_part
After=rc-local.service

[Service]
Type=oneshot
ExecStart=/opt/mount_boot.sh
RemainAfterExit=no

[Install]
WantedBy=basic.target
EOF
systemctl enable mount_boot.service
#-------mount boot part,resize sd part end


#-------etho dhcp
cat >/etc/systemd/network/10-eth0.network <<EOF
[Match]
Name=en*

[Network]
DHCP=yes
EOF

systemctl disable networking
systemctl enable  systemd-networkd
#-------etho dhcp end


#other
apt install  -y libdrm2  libgomp1 libwebp7  libpng-dev  libopus-dev  v4l-utils  ffmpeg usbutils

#pyqt
apt install  -y   qtbase5-dev qtbase5-examples python3-pyqt5
cat << EOF > /etc/profile.d/qt_env.sh
export QT_QPA_PLATFORM=linuxfb
export QT_QPA_FB_DRM=1
export QT_QPA_EGLFS_KMS_CONFIG="/root/kms_config.json"
EOF
cat << EOF > /root/kms_config.json
{
"device": "/dev/dri/card0",
"outputs": [
    { "name": "HDMI1", "format": "argb8888" }
]
}
EOF

#opencv
apt install  -y  python3 python3-pip  python3-opencv

umount  /proc/
umount  /dev/pts

exit
EOFF

sudo tar -czf ubuntu24.tar.gz ubuntu24
# debian13_size="$(( "$(sudo du -sm ubuntu24 | cut -f1 )" + 300 ))"
# mkfs.ext4  -d ubuntu24  -r 1 -N 0 -m 1 -L "rootfs" -O ^64bit ubuntu24.ext4 ${debian13_size}m
# tar -czvf ubuntu24.ext4.tar.gz ubuntu24.ext4
