/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86"
#define DATE "built on: Wed Mar 19 03:21:04 2025 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','o','p','t','/','t',
    'o','o','l','c','h','a','i','n','/','X','u','a','n','t','i','e',
    '-','9','0','0','-','g','c','c','-','l','i','n','u','x','-','6',
    '.','6','.','0','-','g','l','i','b','c','-','x','8','6','_','6',
    '4','-','V','2','.','1','0','.','1','/','b','i','n','/','r','i',
    's','c','v','6','4','-','u','n','k','n','o','w','n','-','l','i',
    'n','u','x','-','g','n','u','-','g','c','c',' ','-','f','P','I',
    'C',' ','-','p','t','h','r','e','a','d',' ','-','W','a','l','l',
    ' ','-','O','3',' ','-','f','o','m','i','t','-','f','r','a','m',
    'e','-','p','o','i','n','t','e','r',' ','-','D','O','P','E','N',
    'S','S','L','_','U','S','E','_','N','O','D','E','L','E','T','E',
    ' ','-','D','L','_','E','N','D','I','A','N',' ','-','D','O','P',
    'E','N','S','S','L','_','P','I','C',' ','-','D','N','D','E','B',
    'U','G','\0'
};
