WIFI_ALG_SRC_LIST :=host/alg_main.c
WIFI_ALG_SRC_LIST +=host/alg_schedule.c
WIFI_ALG_SRC_LIST +=host/alg_autorate.c
WIFI_ALG_SRC_LIST +=host/alg_gla.c
WIFI_ALG_SRC_LIST +=host/alg_probe_common.c
WIFI_ALG_SRC_LIST +=host/alg_tpc.c
WIFI_ALG_SRC_LIST +=host/alg_dbac_hmac.c
WIFI_ALG_SRC_LIST +=host/alg_tx_tb_hmac.c
WIFI_ALG_SRC_LIST +=host/alg_traffic_ctl.c
WIFI_ALG_SRC_LIST +=host/alg_intf_det.c
WIFI_ALG_SRC_LIST +=host/alg_aggr.c
WIFI_ALG_SRC_LIST +=host/alg_rts.c
WIFI_ALG_SRC_LIST +=host/alg_intrf_mode.c

ifeq ($(WIFI_ALG_CCA),y)
WIFI_ALG_SRC_LIST +=host/alg_cca_intrf_mode.c
WIFI_ALG_SRC_LIST +=host/alg_cca_optimize.c
endif

ifeq ($(WIFI_ALG_TEMP_PROTECT),y)
WIFI_ALG_SRC_LIST +=host/alg_temp_protect.c
else
WIFI_ALG_SRC_LIST +=host/alg_temp_protect_basic.c
endif

ifeq ($(WIFI_ALG_TXBF),y)
WIFI_ALG_SRC_LIST +=host/alg_txbf.c
endif

ifeq ($(WIFI_ALG_EDCA),y)
WIFI_ALG_SRC_LIST +=host/alg_edca_intrf_mode.c
WIFI_ALG_SRC_LIST +=host/alg_edca_opt.c
endif

ifeq ($(WIFI_ALG_ANTI_INTF),y)
WIFI_ALG_SRC_LIST +=host/alg_anti_interference.c
endif


WIFI_ALG_INC_LIST := host

WIFI_ALG_MACRO_DEFINES := -D_PRE_WLAN_FEATURE_ANTI_INTERF
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_AUTOAGGR
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_AUTORATE
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_CCA_OPT
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_EDCA_OPT
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_INTF_DET
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_NEGTIVE_DET
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_RTS
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_SCHEDULE
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_SCH_STRATEGY_WMM_ENSURE
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_TEMP_PROTECT
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_TPC
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_TRAFFIC_CTL
WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_TXBF
WIFI_ALG_MACRO_DEFINES += -D_PRE_PRODUCT_ID_IOT_DEV
WIFI_ALG_MACRO_DEFINES += -D_PRE_PRODUCT_ID_IOT_HMAC_DEV
#极限小型化版本关闭DBAC
ifneq ($(WIFI_LITE_EXTREME),y)
    WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_DBAC
    WIFI_ALG_MACRO_DEFINES += -D_PRE_WLAN_FEATURE_GLA
endif