/*
 * Copyright (c) CompanyNameMagicTag 2022-2022. All rights reserved.
 * Description: ws73 rf reg interface and struct adaption
 * Date: 2022-11-12
*/

#ifndef __FE_HAL_RF_PLL_REG_IF_ROM_H__
#define __FE_HAL_RF_PLL_REG_IF_ROM_H__
#include "osal_types.h"
#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif
osal_void hal_rf_set_pll1_en_aac_ct(osal_u16 xWhwGG6w6L_);
osal_void hal_rf_set_pll1_en_aac(osal_u16 xmoOzzC_);
osal_void hal_rf_set_pll1_en_vco_ct(osal_u16 xmoOPCvOCR_);
osal_void hal_rf_set_pll1_en_pll_ld(osal_u16 xmoOGxxOx4_);
osal_void hal_rf_set_pll1_en_phase_slip(osal_u16 xWhwuQGCWwCoBu_);
osal_void hal_rf_set_pll1_pll_dig_ckg_en(osal_u16 xGxxO4l2OCd2Omo_);
osal_void hal_rf_set_pll1_clk_force_on(osal_u16 x6oKwNi_6Wwih_);
osal_void hal_rf_set_pll1_en_dig_clk(osal_u16 xmoO4l2OCxd_);
osal_void hal_rf_set_pll1_en_dig_clk_div2(osal_u16 xmoO4l2OCxdO4lPZ_);
osal_void hal_rf_set_pll1_en_dig_clk_div4(osal_u16 xWhwFBgw6oKwFBqD_);
osal_void hal_rf_set_pll1_en_dig_clk_reserve(osal_u16 xWhwFBgw6oKw_WCW_qW_);
osal_void hal_rf_set_pll1_pll_ct_en_digclk_div2(osal_u16 xuoow6LwWhwFBg6oKwFBqV_);
osal_void hal_rf_set_pll1_pll_dig_ld_ck_en(osal_u16 xGxxO4l2Ox4OCdOmo_);
osal_void hal_rf_set_pll1_pll_mode_sel(osal_u16 xuoowSiFWwCWo_);
osal_void hal_rf_set_pll1_pll_rst_n(osal_u16 xGxxOwsROo_);
osal_void hal_rf_set_pll1_en_pll(osal_u16 xmoOGxx_);
osal_void hal_rf_set_pll2_frac_n_msb(osal_u16 xtwzCOoOIsy_);
osal_void hal_rf_set_pll3_frac_n_lsb(osal_u16 xtwzCOoOxsy_);
osal_void hal_rf_set_pll11_d_pfd_en(osal_u16 x4OGt4Omo_);
osal_void hal_rf_set_pll11_d_pfd_en_up(osal_u16 x4OGt4OmoOSG_);
osal_void hal_rf_set_pll11_d_pfd_en_dn(osal_u16 xFwuNFwWhwFh_);
osal_void hal_rf_set_pll11_d_pfd_force_up(osal_u16 x4OGt4OtvwCmOSG_);
osal_void hal_rf_set_pll11_d_pfd_force_dn(osal_u16 xFwuNFwNi_6WwFh_);
osal_void hal_rf_set_pll11_d_cp_en(osal_u16 x4OCGOmo_);
osal_void hal_rf_set_pll11_d_cp_icp(osal_u16 x4OCGOlCG_);
osal_void hal_rf_set_pll12_d_lpf_en_fll(osal_u16 x4OxGtOmoOtxx_);
osal_void hal_rf_set_pll12_d_lpf_en_swfll(osal_u16 x4OxGtOmoOsqtxx_);
osal_void hal_rf_set_pll12_d_lpf_en_amp(osal_u16 x4OxGtOmoOzIG_);
osal_void hal_rf_set_pll12_d_lpf_amp_itrim(osal_u16 x4OxGtOzIGOlRwlI_);
osal_void hal_rf_set_pll12_d_lpf_dac_vref_sel_ptat(osal_u16 xFwouNwFG6wq_WNwCWowuLGL_);
osal_void hal_rf_set_pll12_d_lpf_dac_vset(osal_u16 x4OxGtO4zCOPsmR_);
osal_void hal_rf_set_pll13_d_lpf_c0(osal_u16 xFwouNw6y_);
osal_void hal_rf_set_pll13_d_lpf_c1(osal_u16 x4OxGtOCr_);
osal_void hal_rf_set_pll13_d_lpf_c3(osal_u16 xFwouNw6k_);
osal_void hal_rf_set_pll13_d_lpf_c4(osal_u16 x4OxGtOCK_);
osal_void hal_rf_set_pll13_d_lpf_r1(osal_u16 xFwouNw_0_);
osal_void hal_rf_set_pll13_d_lpf_r3(osal_u16 x4OxGtOwi_);
osal_void hal_rf_set_pll16_d_vco_ibias_faston(osal_u16 x4OPCvOlylzsOtzsRvo_);
osal_void hal_rf_set_pll16_d_vco_ibias_rc_trim(osal_u16 x4OPCvOlylzsOwCORwlI_);
osal_void hal_rf_set_pll16_d_vco_ibias_ibg_sel(osal_u16 x4OPCvOlylzsOly2Osmx_);
osal_void hal_rf_set_pll16_d_vco_ibias_iptat_sel(osal_u16 xFwq6iwBjBGCwBuLGLwCWo_);
osal_void hal_rf_set_pll16_d_vco_tail_ind_ctrim(osal_u16 xFwq6iwLGBowBhFw6L_BS_);
osal_void hal_rf_set_pll17_d_vco_buf_pll_trim(osal_u16 x4OPCvOyStOGxxORwlI_);
osal_void hal_rf_set_pll17_d_vco_buf_lo_trim(osal_u16 x4OPCvOyStOxvORwlI_);
osal_void hal_rf_set_pll17_d_vco_gm_couple_bypass(osal_u16 xFwq6iwgSw6iduoWwjtuGCC_);
osal_void hal_rf_set_pll17_d_vco_gm_rtrim(osal_u16 x4OPCvO2IOwRwlI_);
osal_void hal_rf_set_pll17_d_vco_ibias_en(osal_u16 xFwq6iwBjBGCwWh_);
osal_void hal_rf_set_pll17_d_vco_ibias_bypass_en(osal_u16 x4OPCvOlylzsOyQGzssOmo_);
osal_void hal_rf_set_pll17_d_vco_var_bias_en(osal_u16 xFwq6iwqG_wjBGCwWh_);
osal_void hal_rf_set_pll17_d_vco_ct_bias_en(osal_u16 x4OPCvOCROylzsOmo_);
osal_void hal_rf_set_pll17_d_vco_ct_bias_sel(osal_u16 x4OPCvOCROylzsOsmx_);
osal_void hal_rf_set_pll18_d_vco_var_bias_faston(osal_u16 x4OPCvOPzwOylzsOtzsRvo_);
osal_void hal_rf_set_pll18_d_vco_var_bias_sel(osal_u16 xFwq6iwqG_wjBGCwCWo_);
osal_void hal_rf_set_pll18_d_vco_buf_dty_cyl_adj(osal_u16 xFwq6iwjdNwFLtw6towGFb_);
osal_void hal_rf_set_pll18_d_vco_var_kp_trim(osal_u16 xFwq6iwqG_wKuwL_BS_);
osal_void hal_rf_set_pll18_d_vco_var_ki_trim(osal_u16 xFwq6iwqG_wKBwL_BS_);
osal_void hal_rf_set_pll19_d_vco_atemp_faston(osal_u16 x4OPCvOzRmIGOtzsRvo_);
osal_void hal_rf_set_pll19_d_vco_atemp_rc_trim(osal_u16 x4OPCvOzRmIGOwCORwlI_);
osal_void hal_rf_set_pll19_d_vco_atemp_gnd_en(osal_u16 x4OPCvOzRmIGO2o4Omo_);
osal_void hal_rf_set_pll19_d_vco_atemp_ptat_mode(osal_u16 x4OPCvOzRmIGOGRzROIv4m_);
osal_void hal_rf_set_pll19_d_vco_atemp_ptat_slope(osal_u16 xFwq6iwGLWSuwuLGLwCoiuW_);
osal_void hal_rf_set_pll19_d_vco_atemp_preload_mode_en(osal_u16 x4OPCvOzRmIGOGwmxvz4OIv4mOmo_);
osal_void hal_rf_set_pll19_d_vco_atemp_dac_vset(osal_u16 xFwq6iwGLWSuwFG6wqCWL_);
osal_void hal_rf_set_pll19_d_vco_bias_always_on(osal_u16 x4OPCvOylzsOzxqzQsOvo_);
osal_void hal_rf_set_pll19_d_vco_reserve(osal_u16 x4OPCvOwmsmwPm_);
osal_void hal_rf_set_pll29_pll_ct_manual_vco1(osal_u16 xuoow6LwSGhdGowq6i0_);
osal_void hal_rf_set_pll29_pll_ct_manual_band_vco1(osal_u16 xuoow6LwSGhdGowjGhFwq6i0_);
osal_void hal_rf_set_pll30_pll_ct_manual_vco2(osal_u16 xGxxOCROIzoSzxOPCvZ_);
osal_void hal_rf_set_pll30_pll_ct_manual_band_vco2(osal_u16 xGxxOCROIzoSzxOyzo4OPCvZ_);
osal_void hal_rf_set_pll31_pll_ctc_bit_sel(osal_u16 xuoow6L6wjBLwCWo_);
osal_u16 hal_rf_get_pll31_pll_ctc_bit_sel(osal_void);
osal_void hal_rf_set_pll31_pll_ct_en_find_band0(osal_u16 xuoow6LwWhwNBhFwjGhFy_);
osal_u16 hal_rf_get_pll31_pll_ct_en_find_band0(osal_void);
osal_void hal_rf_set_pll31_ct_pol(osal_u16 x6Lwuio_);
osal_u16 hal_rf_get_pll31_ct_pol(osal_void);
osal_void hal_rf_set_pll31_ct_band_offset(osal_u16 xCROyzo4OvttsmR_);
osal_u16 hal_rf_get_pll31_ct_band_offset(osal_void);
osal_void hal_rf_set_pll31_pll_ct_coarse_avg_timer(osal_u16 xGxxOCROCvzwsmOzP2ORlImw_);
osal_u16 hal_rf_get_pll31_pll_ct_coarse_avg_timer(osal_void);
osal_void hal_rf_set_pll31_pll_ct_fine_avg_timer(osal_u16 xuoow6LwNBhWwGqgwLBSW__);
osal_u16 hal_rf_get_pll31_pll_ct_fine_avg_timer(osal_void);
osal_u16 hal_rf_get_pll52_ld_dig_done(osal_void);
osal_u16 hal_rf_get_pll52_ld_lock_cnt(osal_void);
osal_u16 hal_rf_get_pll52_ct_band_rb(osal_void);
osal_u16 hal_rf_get_pll53_pll_lock_indicator(osal_void);
osal_u16 hal_rf_get_pll53_ctc_done_flag(osal_void);
osal_u16 hal_rf_get_pll53_ctf_done_flag(osal_void);
osal_u16 hal_rf_get_pll53_ct_end_flag(osal_void);
osal_u16 hal_rf_get_pll53_warm_ready_flag(osal_void);
osal_u16 hal_rf_get_pll53_aac_ct_end_flag(osal_void);
osal_u16 hal_rf_get_pll53_vco_ct_end_flag(osal_void);
osal_u16 hal_rf_get_pll53_phase_ready_flag(osal_void);
osal_u16 hal_rf_get_pll53_close_ready_fll_flag(osal_void);
osal_u16 hal_rf_get_pll53_close_ready_smp_flag(osal_void);
osal_u16 hal_rf_get_pll53_bg_cal_ready_flag(osal_void);
osal_u16 hal_rf_get_pll53_fsm_state_final(osal_void);
#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* end of __FE_HAL_RF_PLL_REG_IF_ROM_H__ */
