"""
Pythonic LVGL wrapper layer.

Re-exports all raw pybind11 bindings from _lvgl and adds convenience
functions. Auto-generated by gen_pybind11.py (IR-based pipeline).
"""

from ._lvgl import *  # noqa: F401,F403 - re-export all raw bindings

def color(r, g, b):
    """Create a color from RGB values (0-255)."""
    return color_make(r, g, b)

def color_from_hex(hex_value):
    """Create a color from a hex value (e.g., 0xFF0000 for red)."""
    return color_hex(hex_value)

def run_loop():
    """Enter the LVGL run loop."""
    driver_backends_run_loop()

def k230_init(v4l2_drm=None, v4l2_drm_run_flag=0):
    """Initialize K230 display driver.

    When v4l2_drm is provided, uses the K230 v4l2-drm backend (DRM_V4L2_K230)
    which shares the DRM display with camera video. When v4l2_drm is None,
    falls back to the standard Linux DRM backend.

    Args:
        v4l2_drm: A V4l2Drm object (from k230_v4l2_drm module), or None
                  to use the default Linux DRM driver.
        v4l2_drm_run_flag: Flag controlling v4l2-drm run behavior (default: 0).
    """
    if v4l2_drm is not None:
        display_ptr = v4l2_drm.get_display_ptr()
    else:
        display_ptr = 0  # NULL pointer -> use default DRM backend
    return k230_driver_init(display_ptr, v4l2_drm_run_flag)

# No __all__ — let all names from ._lvgl (enums, constants, functions,
# widget factories like Label, Button, etc.) and the convenience functions
# above pass through naturally via "from _wrapper import *".