"""
Pythonic LVGL wrapper layer.

Re-exports all raw pybind11 bindings from _lvgl and adds convenience
functions. Auto-generated by gen_pybind11.py (IR-based pipeline).
"""

from ._lvgl import *  # noqa: F401,F403 - re-export all raw bindings


# --- Widget type resolution ---
#
# Objects created via factory functions (lv.btn(), lv.arc(), ...) get a
# _widget_type attribute set by the Python wrapper.  But objects received
# in C callbacks (anim exec_cb, event_cb, etc.) are new LvObjWrapper
# instances created on the C++ side and lack _widget_type.  For those,
# we fall back to _infer_widget_type() which queries the LVGL object class.

def _get_wt(self):
    """Return the widget type string, falling back to LVGL class inspection."""
    wt = getattr(self, '_widget_type', None)
    if wt is not None:
        return wt
    return self._infer_widget_type()



# --- Style Selector enum ---
#
# Replaces magic number 0 in set_style_xxx(value, selector) calls.
# selector = part | state (LVGL convention).
# SELECTOR.DEFAULT = 0 = LV_PART_MAIN | LV_STATE_DEFAULT
#
import enum as _enum

class SELECTOR(_enum.IntEnum):
    """Style selector constants for set_style_xxx(value, selector).

    Combines LVGL part and state into a single selector value.
    DEFAULT = LV_PART_MAIN | LV_STATE_DEFAULT = 0.

    Usage::

        obj.set_style_bg_color(color, lv.SELECTOR.DEFAULT)
        # Equivalent to: obj.set_style_bg_color(color, 0)

    For part+state combinations, use bitwise OR::

        obj.set_style_bg_color(color, lv.PART.KNOB | lv.STATE.FOCUSED)
    """
    DEFAULT = 0

    @staticmethod
    def _combine(part, state=0):
        """Combine a part and state into a selector value."""
        return part | state

def color(r, g, b):
    """Create a color from RGB values (0-255)."""
    return color_make(r, g, b)

def color_from_hex(hex_value):
    """Create a color from a hex value (e.g., 0xFF0000 for red)."""
    return color_hex(hex_value)

def color_from_hex_str(hex_str):
    """Create a color from a hex string (e.g., "#ff0000" or "#FF0000")."""
    return color_hex(int(hex_str.lstrip('#'), 16))

import os as _os
import time as _time

def run():
    """Enter the LVGL run loop (blocking).

    Can be interrupted with Ctrl+C.
    """
    try:
        while True:
            idle = timer_handler()
            _time.sleep(idle / 1000.0)
    except KeyboardInterrupt:
        _os._exit(0)

def init(v4l2_drm=None, v4l2_drm_run_flag=0):
    """Initialize K230 display driver.

    When v4l2_drm is provided, uses the K230 v4l2-drm backend (DRM_V4L2_K230)
    which shares the DRM display with camera video. When v4l2_drm is None,
    falls back to the standard Linux DRM backend.

    Args:
        v4l2_drm: A V4l2Drm object (from k230_v4l2_drm module), or None
                  to use the default Linux DRM driver.
        v4l2_drm_run_flag: Reserved, currently unused (default: 0).
    """
    if v4l2_drm is not None:
        display_ptr = v4l2_drm.get_display_ptr()
    else:
        display_ptr = 0  # NULL pointer -> use default DRM backend
    return k230_driver_init(display_ptr, v4l2_drm_run_flag)



# --- Widget type tagging ---
#
# Wrap ALL factory functions to tag returned Obj instances with
# their widget type. This allows short-name dispatch methods
# (set_rotation, set_value, etc.) to call the correct prefixed
# C++ method based on the widget type.

# obj is a class (not a factory function), so we patch __init__ to set _widget_type
try:
    _obj_orig_init = obj.__init__
    def _obj_patched_init(self, *args, **kwargs):
        _obj_orig_init(self, *args, **kwargs)
        self._widget_type = 'obj'
    obj.__init__ = _obj_patched_init
except NameError:
    pass

try:
    _orig_factory_animimg = animimg
    def animimg(parent=None):
        obj = _orig_factory_animimg(parent)
        obj._widget_type = 'animimg'
        return obj
except NameError:
    pass
try:
    _orig_factory_arc = arc
    def arc(parent=None):
        obj = _orig_factory_arc(parent)
        obj._widget_type = 'arc'
        return obj
except NameError:
    pass
try:
    _orig_factory_bar = bar
    def bar(parent=None):
        obj = _orig_factory_bar(parent)
        obj._widget_type = 'bar'
        return obj
except NameError:
    pass
try:
    _orig_factory_button = button
    def button(parent=None):
        obj = _orig_factory_button(parent)
        obj._widget_type = 'button'
        return obj
except NameError:
    pass
try:
    _orig_factory_canvas = canvas
    def canvas(parent=None):
        obj = _orig_factory_canvas(parent)
        obj._widget_type = 'canvas'
        return obj
except NameError:
    pass
try:
    _orig_factory_chart = chart
    def chart(parent=None):
        obj = _orig_factory_chart(parent)
        obj._widget_type = 'chart'
        return obj
except NameError:
    pass
try:
    _orig_factory_checkbox = checkbox
    def checkbox(parent=None):
        obj = _orig_factory_checkbox(parent)
        obj._widget_type = 'checkbox'
        return obj
except NameError:
    pass
try:
    _orig_factory_dropdown = dropdown
    def dropdown(parent=None):
        obj = _orig_factory_dropdown(parent)
        obj._widget_type = 'dropdown'
        return obj
except NameError:
    pass
try:
    _orig_factory_image = image
    def image(parent=None):
        obj = _orig_factory_image(parent)
        obj._widget_type = 'image'
        return obj
except NameError:
    pass
try:
    _orig_factory_keyboard = keyboard
    def keyboard(parent=None):
        obj = _orig_factory_keyboard(parent)
        obj._widget_type = 'keyboard'
        return obj
except NameError:
    pass
try:
    _orig_factory_label = label
    def label(parent=None):
        obj = _orig_factory_label(parent)
        obj._widget_type = 'label'
        return obj
except NameError:
    pass
try:
    _orig_factory_led = led
    def led(parent=None):
        obj = _orig_factory_led(parent)
        obj._widget_type = 'led'
        return obj
except NameError:
    pass
try:
    _orig_factory_line = line
    def line(parent=None):
        obj = _orig_factory_line(parent)
        obj._widget_type = 'line'
        return obj
except NameError:
    pass
try:
    _orig_factory_list = list
    def list(parent=None):
        obj = _orig_factory_list(parent)
        obj._widget_type = 'list'
        return obj
except NameError:
    pass
try:
    _orig_factory_menu = menu
    def menu(parent=None):
        obj = _orig_factory_menu(parent)
        obj._widget_type = 'menu'
        return obj
except NameError:
    pass
try:
    _orig_factory_msgbox = msgbox
    def msgbox(parent=None):
        obj = _orig_factory_msgbox(parent)
        obj._widget_type = 'msgbox'
        return obj
except NameError:
    pass
try:
    _orig_factory_roller = roller
    def roller(parent=None):
        obj = _orig_factory_roller(parent)
        obj._widget_type = 'roller'
        return obj
except NameError:
    pass
try:
    _orig_factory_scale = scale
    def scale(parent=None):
        obj = _orig_factory_scale(parent)
        obj._widget_type = 'scale'
        return obj
except NameError:
    pass
try:
    _orig_factory_slider = slider
    def slider(parent=None):
        obj = _orig_factory_slider(parent)
        obj._widget_type = 'slider'
        return obj
except NameError:
    pass
try:
    _orig_factory_spinbox = spinbox
    def spinbox(parent=None):
        obj = _orig_factory_spinbox(parent)
        obj._widget_type = 'spinbox'
        return obj
except NameError:
    pass
try:
    _orig_factory_spinner = spinner
    def spinner(parent=None):
        obj = _orig_factory_spinner(parent)
        obj._widget_type = 'spinner'
        return obj
except NameError:
    pass
try:
    _orig_factory_switch = switch
    def switch(parent=None):
        obj = _orig_factory_switch(parent)
        obj._widget_type = 'switch'
        return obj
except NameError:
    pass
try:
    _orig_factory_table = table
    def table(parent=None):
        obj = _orig_factory_table(parent)
        obj._widget_type = 'table'
        return obj
except NameError:
    pass
try:
    _orig_factory_tabview = tabview
    def tabview(parent=None):
        obj = _orig_factory_tabview(parent)
        obj._widget_type = 'tabview'
        return obj
except NameError:
    pass
try:
    _orig_factory_textarea = textarea
    def textarea(parent=None):
        obj = _orig_factory_textarea(parent)
        obj._widget_type = 'textarea'
        return obj
except NameError:
    pass
try:
    _orig_factory_tileview = tileview
    def tileview(parent=None):
        obj = _orig_factory_tileview(parent)
        obj._widget_type = 'tileview'
        return obj
except NameError:
    pass
try:
    _orig_factory_win = win
    def win(parent=None):
        obj = _orig_factory_win(parent)
        obj._widget_type = 'win'
        return obj
except NameError:
    pass


# --- Short-name method aliases on Obj ---
#
# These methods dispatch to the correct prefixed C++ method based
# on the _widget_type tag. For example, set_rotation() calls
# image_set_rotation() or arc_set_rotation() depending on the widget.

try:
    def _add_button_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'list': return self._list_add_button(*args, **kwargs)
        if _wt == 'win': return self._win_add_button(*args, **kwargs)
        raise AttributeError("Obj has no 'add_button' for widget type %s" % _wt)
    obj.add_button = _add_button_dispatch
except NameError:
    pass
try:
    def _add_text_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'list': return self._list_add_text(*args, **kwargs)
        if _wt == 'msgbox': return self._msgbox_add_text(*args, **kwargs)
        if _wt == 'textarea': return self._textarea_add_text(*args, **kwargs)
        raise AttributeError("Obj has no 'add_text' for widget type %s" % _wt)
    obj.add_text = _add_text_dispatch
except NameError:
    pass
try:
    def _add_title_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'msgbox': return self._msgbox_add_title(*args, **kwargs)
        if _wt == 'win': return self._win_add_title(*args, **kwargs)
        raise AttributeError("Obj has no 'add_title' for widget type %s" % _wt)
    obj.add_title = _add_title_dispatch
except NameError:
    pass
try:
    def _close_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'dropdown': return self._dropdown_close(*args, **kwargs)
        if _wt == 'msgbox': return self._msgbox_close(*args, **kwargs)
        raise AttributeError("Obj has no 'close' for widget type %s" % _wt)
    obj.close = _close_dispatch
except NameError:
    pass
try:
    def _get_button_text_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'keyboard': return self._keyboard_get_button_text(*args, **kwargs)
        if _wt == 'list': return self._list_get_button_text(*args, **kwargs)
        raise AttributeError("Obj has no 'get_button_text' for widget type %s" % _wt)
    obj.get_button_text = _get_button_text_dispatch
except NameError:
    pass
try:
    def _get_content_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'msgbox': return self._msgbox_get_content(*args, **kwargs)
        if _wt == 'tabview': return self._tabview_get_content(*args, **kwargs)
        if _wt == 'win': return self._win_get_content(*args, **kwargs)
        raise AttributeError("Obj has no 'get_content' for widget type %s" % _wt)
    obj.get_content = _get_content_dispatch
except NameError:
    pass
try:
    def _get_header_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'msgbox': return self._msgbox_get_header(*args, **kwargs)
        if _wt == 'win': return self._win_get_header(*args, **kwargs)
        raise AttributeError("Obj has no 'get_header' for widget type %s" % _wt)
    obj.get_header = _get_header_dispatch
except NameError:
    pass
try:
    def _get_max_value_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_get_max_value(*args, **kwargs)
        if _wt == 'bar': return self._bar_get_max_value(*args, **kwargs)
        if _wt == 'slider': return self._slider_get_max_value(*args, **kwargs)
        if _wt == 'spinbox': return self._spinbox_get_max_value(*args, **kwargs)
        raise AttributeError("Obj has no 'get_max_value' for widget type %s" % _wt)
    obj.get_max_value = _get_max_value_dispatch
except NameError:
    pass
try:
    def _get_min_value_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_get_min_value(*args, **kwargs)
        if _wt == 'bar': return self._bar_get_min_value(*args, **kwargs)
        if _wt == 'slider': return self._slider_get_min_value(*args, **kwargs)
        if _wt == 'spinbox': return self._spinbox_get_min_value(*args, **kwargs)
        raise AttributeError("Obj has no 'get_min_value' for widget type %s" % _wt)
    obj.get_min_value = _get_min_value_dispatch
except NameError:
    pass
try:
    def _get_mode_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_get_mode(*args, **kwargs)
        if _wt == 'bar': return self._bar_get_mode(*args, **kwargs)
        if _wt == 'keyboard': return self._keyboard_get_mode(*args, **kwargs)
        if _wt == 'scale': return self._scale_get_mode(*args, **kwargs)
        if _wt == 'slider': return self._slider_get_mode(*args, **kwargs)
        raise AttributeError("Obj has no 'get_mode' for widget type %s" % _wt)
    obj.get_mode = _get_mode_dispatch
except NameError:
    pass
try:
    def _get_option_count_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'dropdown': return self._dropdown_get_option_count(*args, **kwargs)
        if _wt == 'roller': return self._roller_get_option_count(*args, **kwargs)
        raise AttributeError("Obj has no 'get_option_count' for widget type %s" % _wt)
    obj.get_option_count = _get_option_count_dispatch
except NameError:
    pass
try:
    def _get_options_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'dropdown': return self._dropdown_get_options(*args, **kwargs)
        if _wt == 'roller': return self._roller_get_options(*args, **kwargs)
        raise AttributeError("Obj has no 'get_options' for widget type %s" % _wt)
    obj.get_options = _get_options_dispatch
except NameError:
    pass
try:
    def _get_orientation_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'bar': return self._bar_get_orientation(*args, **kwargs)
        if _wt == 'slider': return self._slider_get_orientation(*args, **kwargs)
        if _wt == 'switch': return self._switch_get_orientation(*args, **kwargs)
        raise AttributeError("Obj has no 'get_orientation' for widget type %s" % _wt)
    obj.get_orientation = _get_orientation_dispatch
except NameError:
    pass
try:
    def _get_point_count_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'chart': return self._chart_get_point_count(*args, **kwargs)
        if _wt == 'line': return self._line_get_point_count(*args, **kwargs)
        raise AttributeError("Obj has no 'get_point_count' for widget type %s" % _wt)
    obj.get_point_count = _get_point_count_dispatch
except NameError:
    pass
try:
    def _get_rotation_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_get_rotation(*args, **kwargs)
        if _wt == 'image': return self._image_get_rotation(*args, **kwargs)
        if _wt == 'scale': return self._scale_get_rotation(*args, **kwargs)
        raise AttributeError("Obj has no 'get_rotation' for widget type %s" % _wt)
    obj.get_rotation = _get_rotation_dispatch
except NameError:
    pass
try:
    def _get_selected_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'dropdown': return self._dropdown_get_selected(*args, **kwargs)
        if _wt == 'roller': return self._roller_get_selected(*args, **kwargs)
        raise AttributeError("Obj has no 'get_selected' for widget type %s" % _wt)
    obj.get_selected = _get_selected_dispatch
except NameError:
    pass
try:
    def _get_text_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'checkbox': return self._checkbox_get_text(*args, **kwargs)
        if _wt == 'dropdown': return self._dropdown_get_text(*args, **kwargs)
        if _wt == 'label': return self._label_get_text(*args, **kwargs)
        raise AttributeError("Obj has no 'get_text' for widget type %s" % _wt)
    obj.get_text = _get_text_dispatch
except NameError:
    pass
try:
    def _get_value_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_get_value(*args, **kwargs)
        if _wt == 'bar': return self._bar_get_value(*args, **kwargs)
        if _wt == 'slider': return self._slider_get_value(*args, **kwargs)
        if _wt == 'spinbox': return self._spinbox_get_value(*args, **kwargs)
        raise AttributeError("Obj has no 'get_value' for widget type %s" % _wt)
    obj.get_value = _get_value_dispatch
except NameError:
    pass
try:
    def _is_symmetrical_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'bar': return self._bar_is_symmetrical(*args, **kwargs)
        if _wt == 'slider': return self._slider_is_symmetrical(*args, **kwargs)
        raise AttributeError("Obj has no 'is_symmetrical' for widget type %s" % _wt)
    obj.is_symmetrical = _is_symmetrical_dispatch
except NameError:
    pass
try:
    def _set_cursor_pos_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'spinbox': return self._spinbox_set_cursor_pos(*args, **kwargs)
        if _wt == 'textarea': return self._textarea_set_cursor_pos(*args, **kwargs)
        raise AttributeError("Obj has no 'set_cursor_pos' for widget type %s" % _wt)
    obj.set_cursor_pos = _set_cursor_pos_dispatch
except NameError:
    pass
try:
    def _set_max_value_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_set_max_value(*args, **kwargs)
        if _wt == 'bar': return self._bar_set_max_value(*args, **kwargs)
        if _wt == 'scale': return self._scale_set_max_value(*args, **kwargs)
        if _wt == 'slider': return self._slider_set_max_value(*args, **kwargs)
        if _wt == 'spinbox': return self._spinbox_set_max_value(*args, **kwargs)
        raise AttributeError("Obj has no 'set_max_value' for widget type %s" % _wt)
    obj.set_max_value = _set_max_value_dispatch
except NameError:
    pass
try:
    def _set_min_value_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_set_min_value(*args, **kwargs)
        if _wt == 'bar': return self._bar_set_min_value(*args, **kwargs)
        if _wt == 'scale': return self._scale_set_min_value(*args, **kwargs)
        if _wt == 'slider': return self._slider_set_min_value(*args, **kwargs)
        if _wt == 'spinbox': return self._spinbox_set_min_value(*args, **kwargs)
        raise AttributeError("Obj has no 'set_min_value' for widget type %s" % _wt)
    obj.set_min_value = _set_min_value_dispatch
except NameError:
    pass
try:
    def _set_mode_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_set_mode(*args, **kwargs)
        if _wt == 'bar': return self._bar_set_mode(*args, **kwargs)
        if _wt == 'keyboard': return self._keyboard_set_mode(*args, **kwargs)
        if _wt == 'scale': return self._scale_set_mode(*args, **kwargs)
        if _wt == 'slider': return self._slider_set_mode(*args, **kwargs)
        raise AttributeError("Obj has no 'set_mode' for widget type %s" % _wt)
    obj.set_mode = _set_mode_dispatch
except NameError:
    pass
try:
    def _set_options_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'dropdown': return self._dropdown_set_options(*args, **kwargs)
        if _wt == 'roller': return self._roller_set_options(*args, **kwargs)
        raise AttributeError("Obj has no 'set_options' for widget type %s" % _wt)
    obj.set_options = _set_options_dispatch
except NameError:
    pass
try:
    def _set_orientation_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'bar': return self._bar_set_orientation(*args, **kwargs)
        if _wt == 'slider': return self._slider_set_orientation(*args, **kwargs)
        if _wt == 'switch': return self._switch_set_orientation(*args, **kwargs)
        raise AttributeError("Obj has no 'set_orientation' for widget type %s" % _wt)
    obj.set_orientation = _set_orientation_dispatch
except NameError:
    pass
try:
    def _set_range_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_set_range(*args, **kwargs)
        if _wt == 'bar': return self._bar_set_range(*args, **kwargs)
        if _wt == 'scale': return self._scale_set_range(*args, **kwargs)
        if _wt == 'slider': return self._slider_set_range(*args, **kwargs)
        if _wt == 'spinbox': return self._spinbox_set_range(*args, **kwargs)
        raise AttributeError("Obj has no 'set_range' for widget type %s" % _wt)
    obj.set_range = _set_range_dispatch
except NameError:
    pass
try:
    def _set_rotation_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_set_rotation(*args, **kwargs)
        if _wt == 'image': return self._image_set_rotation(*args, **kwargs)
        if _wt == 'scale': return self._scale_set_rotation(*args, **kwargs)
        raise AttributeError("Obj has no 'set_rotation' for widget type %s" % _wt)
    obj.set_rotation = _set_rotation_dispatch
except NameError:
    pass
try:
    def _set_selected_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'dropdown': return self._dropdown_set_selected(*args, **kwargs)
        if _wt == 'roller': return self._roller_set_selected(*args, **kwargs)
        raise AttributeError("Obj has no 'set_selected' for widget type %s" % _wt)
    obj.set_selected = _set_selected_dispatch
except NameError:
    pass
try:
    def _set_start_value_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'bar': return self._bar_set_start_value(*args, **kwargs)
        if _wt == 'slider': return self._slider_set_start_value(*args, **kwargs)
        raise AttributeError("Obj has no 'set_start_value' for widget type %s" % _wt)
    obj.set_start_value = _set_start_value_dispatch
except NameError:
    pass
try:
    def _set_text_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'checkbox': return self._checkbox_set_text(*args, **kwargs)
        if _wt == 'dropdown': return self._dropdown_set_text(*args, **kwargs)
        if _wt == 'label': return self._label_set_text(*args, **kwargs)
        if _wt == 'textarea': return self._textarea_set_text(*args, **kwargs)
        raise AttributeError("Obj has no 'set_text' for widget type %s" % _wt)
    obj.set_text = _set_text_dispatch
except NameError:
    pass
try:
    def _set_text_static_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'checkbox': return self._checkbox_set_text_static(*args, **kwargs)
        if _wt == 'dropdown': return self._dropdown_set_text_static(*args, **kwargs)
        if _wt == 'label': return self._label_set_text_static(*args, **kwargs)
        raise AttributeError("Obj has no 'set_text_static' for widget type %s" % _wt)
    obj.set_text_static = _set_text_static_dispatch
except NameError:
    pass
try:
    def _set_value_dispatch(self, *args, **kwargs):
        _wt = _get_wt(self)
        if _wt == 'arc': return self._arc_set_value(*args, **kwargs)
        if _wt == 'bar': return self._bar_set_value(*args, **kwargs)
        if _wt == 'slider': return self._slider_set_value(*args, **kwargs)
        if _wt == 'spinbox': return self._spinbox_set_value(*args, **kwargs)
        raise AttributeError("Obj has no 'set_value' for widget type %s" % _wt)
    obj.set_value = _set_value_dispatch
except NameError:
    pass

# --- Bitmask enum patches ---
#
# pybind11 enum | returns int, not the enum type, so add_flag(OBJ_FLAG.A | OBJ_FLAG.B)
# fails. Patch these methods to cast the int back to the enum type.

try:
    _orig_add_flag = obj.add_flag
    def add_flag(self, f):
        _orig_add_flag(self, OBJ_FLAG(int(f)))
    obj.add_flag = add_flag
except NameError:
    pass
try:
    _orig_remove_flag = obj.remove_flag
    def remove_flag(self, f):
        _orig_remove_flag(self, OBJ_FLAG(int(f)))
    obj.remove_flag = remove_flag
except NameError:
    pass
try:
    _orig_set_flag = obj.set_flag
    def set_flag(self, f, v):
        _orig_set_flag(self, OBJ_FLAG(int(f)), v)
    obj.set_flag = set_flag
except NameError:
    pass
try:
    _orig_has_flag = obj.has_flag
    def has_flag(self, f):
        return _orig_has_flag(self, OBJ_FLAG(int(f)))
    obj.has_flag = has_flag
except NameError:
    pass
try:
    _orig_has_flag_any = obj.has_flag_any
    def has_flag_any(self, f):
        return _orig_has_flag_any(self, OBJ_FLAG(int(f)))
    obj.has_flag_any = has_flag_any
except NameError:
    pass
try:
    _orig_add_state = obj.add_state
    def add_state(self, s):
        _orig_add_state(self, STATE(int(s)))
    obj.add_state = add_state
except NameError:
    pass
try:
    _orig_remove_state = obj.remove_state
    def remove_state(self, s):
        _orig_remove_state(self, STATE(int(s)))
    obj.remove_state = remove_state
except NameError:
    pass