#!/bin/sh
bootddev=$(cat /proc/cmdline  | sed  -n  "s#root=\(\/dev\/mmcblk[0-9]\).*#\1#p" )


if [ -f /first_boot_flag ]; then
    echo "first boot flag"
    echo "${bootddev}   0x1e0000 0x10000" >/etc/fw_env.config
	printf "fix\n" | parted ---pretend-input-tty ${bootddev} print  >/dev/null 2>&1
    sd_size=$(parted ${bootddev} print | grep ${bootddev} | cut -d: -f2)
    parted ${bootddev} resizepart 2 ${sd_size}; resize2fs ${bootddev}p2
    rm -rf /first_boot_flag
fi
