/*
 * Copyright (c) CompanyNameMagicTag 2022-2022. All rights reserved.
 * Description: usbd turbo register config.
 * Author: Driver Group
 * Create: 2022-02-16
 */

#ifndef __USB_TURBO_REG_REG_OFFSET_H__
#define __USB_TURBO_REG_REG_OFFSET_H__

/* USB_TURBO_REG Base address of Module's Register */
#define USB_TURBO_REG_BASE (0x4800e000)

/* **************************************************************************** */
/*                      HH503 USB_TURBO_REG Registers' Definitions                            */
/* **************************************************************************** */

#define USB_TURBO_REG_USB_TURBO_CFG_REG (USB_TURBO_REG_BASE + 0x0) /* USB TURBO 配置寄存器 */
#define USB_TURBO_REG_USB_TURBO_STS_REG (USB_TURBO_REG_BASE + 0x4) /* USB TURBO 状态寄存器 */
#define USB_TURBO_REG_USB_TURBO_GEVNTCOUNT_CFG_REG \
    (USB_TURBO_REG_BASE + 0x8) /* USB TURBO GEVNTCOUNT配置寄存器 */
#define USB_TURBO_REG_USB_TURBO_BUS_ERR_ADDR_REG \
    (USB_TURBO_REG_BASE + 0xC) /* USB TURBO 总线错误地址寄存器 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW0_REG \
    (USB_TURBO_REG_BASE + 0x10) /* USB TURBO TRB BUFFER寄存器0 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW1_REG \
    (USB_TURBO_REG_BASE + 0x14) /* USB TURBO TRB BUFFER寄存器1 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW2_REG \
    (USB_TURBO_REG_BASE + 0x18) /* USB TURBO TRB BUFFER寄存器2 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW3_REG \
    (USB_TURBO_REG_BASE + 0x1C) /* USB TURBO TRB BUFFER寄存器3 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW4_REG \
    (USB_TURBO_REG_BASE + 0x20) /* USB TURBO TRB BUFFER寄存器4 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW5_REG \
    (USB_TURBO_REG_BASE + 0x24) /* USB TURBO TRB BUFFER寄存器5 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW6_REG \
    (USB_TURBO_REG_BASE + 0x28) /* USB TURBO TRB BUFFER寄存器6 */
#define USB_TURBO_REG_USB_TURBO_TRB_BUFFER_DW7_REG \
    (USB_TURBO_REG_BASE + 0x2C) /* USB TURBO TRB BUFFER寄存器7 */
#define USB_TURBO_REG_USB_TURBO_DATA_BUFFER_DW0_REG \
    (USB_TURBO_REG_BASE + 0x30) /* USB TURBO DATA BUFFER寄存器0 */
#define USB_TURBO_REG_USB_TURBO_DATA_BUFFER_DW1_REG \
    (USB_TURBO_REG_BASE + 0x34) /* USB TURBO DATA BUFFER寄存器1 */
#define USB_TURBO_REG_USB_TURBO_DATA_BUFFER_DW2_REG \
    (USB_TURBO_REG_BASE + 0x38) /* USB TURBO DATA BUFFER寄存器2 */
#define USB_TURBO_REG_USB_TURBO_DATA_BUFFER_DW3_REG \
    (USB_TURBO_REG_BASE + 0x3C) /* USB TURBO DATA BUFFER寄存器3 */
#define USB_TURBO_REG_USB_TURBO_CMD_SETUP_ADDR_REG \
    (USB_TURBO_REG_BASE + 0x40) /* USB TURBO SETUP命令地址寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_SETUP_PARAM0_REG \
    (USB_TURBO_REG_BASE + 0x44) /* USB TURBO SETUP命令PARAM0寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_SETUP_PARAM1_REG \
    (USB_TURBO_REG_BASE + 0x48) /* USB TURBO SETUP命令PARAM1寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_SETUP_PARAM2_REG \
    (USB_TURBO_REG_BASE + 0x4C) /* USB TURBO SETUP命令PARAM2寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_SETUP_DEPCMD_REG \
    (USB_TURBO_REG_BASE + 0x50) /* USB TURBO SETUP命令DEPCMD寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAIN_ADDR_REG \
    (USB_TURBO_REG_BASE + 0x54) /* USB TURBO DATAIN命令地址寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAIN_PARAM0_REG \
    (USB_TURBO_REG_BASE + 0x58) /* USB TURBO DATAIN命令PARAM0寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAIN_PARAM1_REG \
    (USB_TURBO_REG_BASE + 0x5C) /* USB TURBO DATAIN命令PARAM1寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAIN_PARAM2_REG \
    (USB_TURBO_REG_BASE + 0x60) /* USB TURBO DATAIN命令PARAM2寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAIN_DEPCMD_REG \
    (USB_TURBO_REG_BASE + 0x64) /* USB TURBO DATAIN命令DEPCMD寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAOUT_ADDR_REG \
    (USB_TURBO_REG_BASE + 0x68) /* USB TURBO DATAOUT命令地址寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAOUT_PARAM0_REG \
    (USB_TURBO_REG_BASE + 0x6C) /* USB TURBO DATAOUT命令PARAM0寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAOUT_PARAM1_REG \
    (USB_TURBO_REG_BASE + 0x70) /* USB TURBO DATAOUT命令PARAM1寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAOUT_PARAM2_REG \
    (USB_TURBO_REG_BASE + 0x74) /* USB TURBO DATAOUT命令PARAM2寄存器 */
#define USB_TURBO_REG_USB_TURBO_CMD_DATAOUT_DEPCMD_REG \
    (USB_TURBO_REG_BASE + 0x78) /* USB TURBO DATAOUT命令DEPCMD寄存器 */
#define USB_TURBO_REG_USB_TURBO_TARGET_REG_BACK_UP_ADDR_REG \
    (USB_TURBO_REG_BASE + 0x100) /* USB_TURBO 目标寄存器备份地址寄存器 */

#endif // __USB_TURBO_REG_REG_OFFSET_H__
